### ISSUE TITLE
Additional backends, File path completion, Dabbrev

### ISSUE THREAD

**Issue by manuel-uberti** [minad/corfu#9] opened 2021-04-19 07:15 UTC
Hi,

I don't know if I am getting this wrong, but this is something that usually works with Company. From `emacs -Q`:

```emacs-lisp
(corfu-mode)
(setq completion-styles '(orderless)
      completion-category-defaults nil
      completion-category-overrides '((file (styles . (partial-completion)))))
(setq tab-always-indent 'complete)

(setq dir "~/
```
If I press `TAB` after that last `/` I do not get completion offered, whereas `M-x company-complete` offers me the directories in my home directory.

**Comment by minad** [comment] 2021-04-19 08:51
This is not a bug in corfu but actually a nice feature of company as far as I know. 

1. Company has additional backends, I suspect in this case the `company-files` backend performs the completion. Support for file name completion could be added to corfu by writing an additional capf function which does just the same as `company-files`. Probably such a capf function should be put directly into Emacs.
2. Furthermore there is the possibility to specify multiple backends at once. This is harder, one could write a multi-capf which then calls other capfs recursively.

~~~ elisp
(defcustom company-backends `(company-bbdb
                              ,@(unless (version<= "26" emacs-version)
                                  (list 'company-nxml))
                              ,@(unless (version<= "26" emacs-version)
                                  (list 'company-css))
                              company-semantic
                              company-cmake
                              company-capf ;; <--- (1) capf fails
                              company-clang
                              company-files ;; <--- (1) files taes over
                              (company-dabbrev-code company-gtags company-etags
                               company-keywords) ;; <--- (2) here even multiple backends are queried at the same time!
                              company-oddmuse company-dabbrev)
~~~

**Comment by manuel-uberti** [comment] 2021-04-19 09:07
Again, thanks for the kind explanation. This not a bug, then, but a feature request, so feel free to close this if you want.

**Comment by manuel-uberti** [comment] 2021-04-19 09:16
Actually, if do not want to add unnecessary complexity here, I can get the same path completion through the minibuffer + Embark to insert the current candidate. Not as quick as with Company, but I get what I want, and considering this is not something I do very often, it's more than enough for me.

**Comment by minad** [comment] 2021-04-19 10:48
Yes, this feature cannot be implemented here. It should probably be implemented as a separate file-capf package or directly inside Emacs core.

**Comment by jdtsmith** [comment] 2021-07-17 22:48
`comint-completion-at-point`, which is already included in Emacs, includes a quite capable CAPF with filename completer. No reason it has to work only in comint modes.  I just tested the following in Elisp buffers, and get good in-buffer filename completion:

```elisp
(setq completion-at-point-functions '(elisp-completion-at-point comint--complete-file-name-data)
      comint-completion-addsuffix nil)
```

**Comment by minad** [comment] 2021-07-17 22:53
@jdtsmith This works indeed great! I want to have this in the documentation. Would you like to create PR - maybe with a list of modes where this works? It works as long as the first capf does not set in within strings and gives up, such that the comint capf can take over.

**Comment by jdtsmith** [comment] 2021-07-18 20:39
I see, you meant document the _multi-capf_ part.  I've always understood that to be a generic part of capf functionality — as long as the earlier capf functions on the list return an immediate `nil` (e.g. because point is in a string, etc.), the next ones get called [1].  

In addition to the generic multi-capf possibility, there is also the `:exclusive 'no` extra property a capf can return, which means something like "_even if I say I can complete here, consult my completion table (function), and if **it** returns no matches, just continue on to later entries in c-a-p-f_".  

Since the way many fancy completion styles work require calling `try-completion` lots of different ways, the capf code ends up calling `try-completion` early and often (like on every key press for company), which can lead to issues if gathering completion choices is slow.  

If there were one more opttion for `:exclusive` like `'collect`, which would mean even if a completion table returns results, proceed to the next capf and append its results to the possible completions list, then you'd basically be able to do everything company can.

[1] `comint` in fact adds `comint-completion-at-point` to `completion-at-point-functions` for just this reason.

**Comment by jdtsmith** [comment] 2021-07-18 20:47
BTW, an obvious CAPF to write that would make good use of `:exclusive 'no` is one that hooks into `dabbrev-complete`, and gets put at the end of c-a-p-f.  That way if the nominal (LSP, etc.) completion doesn't come up with any result, you're offered matching choices from the buffer.  Seems pretty simple, can't believe it's not out there (other than in company).

**Comment by minad** [comment] 2021-07-23 22:17
I am currently using experimenting with these backends:

~~~ elisp
  (defvar comint-completion-addsuffix)
  (autoload 'comint--match-partial-filename "comint")
  (defun +file-completion-at-point-function ()
    "File name completion-at-point-function."
    (when (comint--match-partial-filename)
      (let ((comint-completion-addsuffix))
        (when-let (result (comint--complete-file-name-data))
          `(,@result
            :exclusive no
            :annotation-function ,(lambda (_) " (File)"))))))

  (autoload 'dabbrev--reset-global-variables "dabbrev")
  (defun +dabbrev-completion-at-point-function ()
    (dabbrev--reset-global-variables)
    (let* ((inhibit-message t)
           (message-log-max nil)
           (abbrev (dabbrev--abbrev-at-point))
           (min-len (+ 2 (length abbrev))))
      (pcase (and (not (string-match-p "[ \t]" abbrev))
                  ;; Interruptible scanning, good idea?
                  (while-no-input
                    (or (dabbrev--find-all-expansions
                         abbrev (dabbrev--ignore-case-p abbrev))
                        t)))
        ('nil (keyboard-quit))
        ('t nil)
        (table
         ;; Ignore completions which are too short
         (setq table (seq-remove (lambda (x) (< (length x) min-len)) table))
         (when table
           `(,(progn (search-backward abbrev) (point))
             ,(progn (search-forward abbrev) (point))
             ,table
             :exclusive 'no
             :annotation-function ,(lambda (_) " (Dabbrev)")))))))
~~~

I would be interested in feedback. Maybe I will package these functions up in a separate package. Furthermore it would be interesting to construct a multi-capf, which *merges* different backends.

**Comment by jdtsmith** [comment] 2021-07-23 23:28
(Can't test for a while as I'm traveling.)  Why not just use the in-built comint file name CAPF as is?  Love the Dabbrev idea though.

Not a deep CAPF expert, but I  usually see people return (and I've returned)  a `(lambda (string pred action) ...` for the table (after deciding whether they _want_ to complete there at all).  Then in the lambda you can deal with what you want, and finally punt the rest to `completion-table-dynamic`, or maybe `completion-table-with-cache`, or `completion-table-with-context`.   

People do seem quite attached to "merged" completion backends ala company.  I mentioned elsewhere but an important caveat comes in minibuffer.el  where `exclusive 'no` is detected (followed by an immediate `try-completion`):

```
;; FIXME: Here we'd need to decide whether there are
;; valid completions against the current text.  But this depends
;; on the actual completion UI (e.g. with the default completion
;; it depends on completion-style) ;-(
;; We approximate this result by checking whether prefix
;; completion might work, which means that non-prefix completion
;; will not work (or not right) for completion functions that
;; are non-exclusive.
```

To me it's weird that CAPF's themselves get to decide whether to continue on.  Seems like a user choice to me. 

I bet if you post the dabbrev one on emacs-devel Stefan will jump in there with suggestions. Most of what I learned on the topic I learned from him.

**Comment by minad** [comment] 2021-07-23 23:40
> Why not just use the in-built comint file name CAPF as is (comint--complete-file-name-data looks to be a perfectly good capf)? 

It triggers too often, even if you complete empty strings. Therefore I check `(comint--match-partial-filename)` first. Furthermore I can add comint-completion-addsuffix etc. But besides that the comint capf is good as is.

> Not a deep CAPF expert, but I usually see people return (and I've returned) a (lambda (string pred action) ... for the table (after deciding whether they want to complete there at all).

There is no advantage in using a dynamic table here, since the list of completions is computed right away. However I should probably specify the completion category via the completion metadata. Then I need a lambda.

> People do seem quite attached to "merged" completion backends ala company. I mentioned elsewhere but an important caveat comes in minibuffer.el where exclusive 'no is detected (followed by an immediate try-completion):

I don't see how this comment is related to merged completion tables. The comment talks about how one decides which table gets to run.

**Comment by jdtsmith** [comment] 2021-07-24 02:01
> > People do seem quite attached to "merged" completion backends ala company. I mentioned elsewhere but an important caveat comes in minibuffer.el where exclusive 'no is detected (followed by an immediate try-completion):
> 
> I don't see how this comment is related to merged completion tables. The comment talks about how one decides which table gets to run - basically what you outlined in your [#9 (comment)](https://github.com/minad/corfu/issues/9#issuecomment-882113895).

Only related in the "extend to `'collect`" sense. In fact thinking about it, _merged_ completions would be simpler and not be subject to this issue, because you don't have to first determine if a capf will return anything.   

> A multi-capf would work like your 'collect proposal or one could write a table which calls the other completion tables and returns the collected results. The caveat mentioned in the comment would not apply to the merging of the tables if all results are taken into consideration.

That sounds like a challenging thing to get working well for all the Capf's out there, since there is such diversity in how they return results, interact with completion-styles etc.  But a simple version seems indeeds straightforward.

**Comment by jdtsmith** [comment] 2021-07-24 03:02
OK gave the dabbrev one a quick try.  It must be pretty early on in capf or other exclusive's will block it (hence my comment on why this should be a user decision, not a capf decision).  It seems to work OK, sometimes a bit slow to compute the abbrevs even in a modest sized buffer.  It does quit with a ding quite often due to the `('nil (keyboard-quit))`.  It also gives way too many matches compared to normal in-buffer `dabbrev-completion` (not even sure where it is getting them).  Did you notice that `dabbrev-completion` has its own completion table lambda built in, metadata and all (which it hands to `completion-in-region`)?   

Also not sure how I feel about where it works: comments and strings. The main issue here is that it _only_ works in comments and strings, i.e. wherever e.g. `elisp-completion-at-point` is unwilling to try.  Of course the ideal thing would be to invert that logic, and work exclusively in the same places `elisp-completion-at-point` will try, in case it fails.  I.e. we need to turn on `:exclusive 'no` for `elisp-completion-at-point`.

**Comment by minad** [comment] 2021-07-24 05:36
> It must be pretty early on in capf or other exclusive's will block it (hence my comment on why this should be a user decision, not a capf decision). 

Yes, but in programming modes you certainly don't want to have it before the main capf, otherwise the dabbrev capf will always take over. For this to work one would need a merging multi-capf.

> It seems to work OK, sometimes a bit slow to compute the abbrevs even in a modest sized buffer.

I also observed this too. It may be the case that the dabbrev implementation is not good enough to be used here, since it does not perform sufficient caching. This would be very unfortunate given that there are multiple dabbrev implementations around already.

* dabbrev
* hippie uses its own dabbrev
* company uses its own dabbrev

> It does quit with a ding quite often due to the ('nil (keyboard-quit)).

Oh, I made a mistake here, the while-no-input only returns nil when explicitly quitting. But I have this string-match check before, which breaks this.

>  It also gives way too many matches compared to normal in-buffer dabbrev-completion (not even sure where it is getting them). Did you notice that dabbrev-completion has its own completion table lambda built in, metadata and all (which it hands to completion-in-region)?

Of course I am aware of the table in dabbrev.el. Unfortunately I cannot reuse it here, since it is baked into this function and only made available to `completion-in-region`. However I could steal the explicit implementation. Probably this solves the issue with the too many matches.

But this is a prototype/poc here - due to the slowness this may not even work out in this form :(
Therefore I didn't spent the time yet to refine the filtering accordingly.

>  Of course the ideal thing would be to invert that logic, and work exclusively in the same places elisp-completion-at-point will try, in case it fails. I.e. we need to turn on :exclusive 'no for elisp-completion-at-point.

Agree. But turning on :exclusive=no happens outside the dabbrev capf, one should advise the elisp capf.

**Comment by minad** [comment] 2021-07-24 06:10
Improved version:

~~~ elisp
  (autoload 'dabbrev--reset-global-variables "dabbrev")
  (defun +dabbrev-completion-at-point-function ()
    (let ((abbrev (ignore-errors (dabbrev--abbrev-at-point))))
      (when (and abbrev (not (string-match-p "[ \t]" abbrev)))
        (pcase ;; Interruptible scanning, good idea?
            (while-no-input
              (let ((dabbrev-check-all-buffers nil)
                    (dabbrev-check-other-buffers nil)
                    (inhibit-message t)
                    (message-log-max nil))
                (dabbrev--reset-global-variables)
                (or (dabbrev--find-all-expansions
                     abbrev (dabbrev--ignore-case-p abbrev))
                    t)))
          ('nil (keyboard-quit))
          ('t nil)
          (table
           ;; Ignore completions which are too short
           (let ((min-len (+ 4 (length abbrev))))
             (setq table (seq-remove (lambda (x) (< (length x) min-len)) table)))
           (when table
             `(,(progn (search-backward abbrev) (point))
               ,(progn (search-forward abbrev) (point))
               ,(lambda (str pred action)
                  (if (eq action 'metadata)
                      '(metadata
                        (category . dabbrev)
                        (display-sort-function . identity)
                        (cycle-sort-function . identity))
                    (complete-with-action action table str pred)))
               :exclusive 'no
               :annotation-function ,(lambda (_) " (Dabbrev)"))))))))
~~~

**Comment by jdtsmith** [comment] 2021-07-24 12:27
Hmm, it's still picking up tons of words for me.  Both of those variables are `t` but you do let-bind them.  Looking closer, it appears dabbrev uses some internal mirrors of these variables (`dabbrev--check-other-buffers` etc.) and resets them to their global values periodically (`dabbrev--reset-global-variables`), defeating your dynamic bindings.  I had to:

```elisp
(setq dabbrev-check-all-buffers nil
      dabbrev-check-other-buffers nil)
```

to get dabbrev to draw matches only from this buffer. 

Some people have been praising [fancy-dabbrev](https://github.com/jrosdahl/fancy-dabbrev), which just auto-populates one match from dabbrev with a timer for immediate confirmation.  This reminds me of the feature of company I still miss in corfu: if there is ever _one and only one_ match, it removes the popup and pre-populates the _buffer_ with just the (fontified) match, which can be Return confirmed (with no other confirmation possible):

![image](https://user-images.githubusercontent.com/93749/126868197-9b4da7d8-19a7-4ef3-8842-0c41ff878195.png)

**Comment by jdtsmith** [comment] 2021-07-24 12:43
I notice the actual `dabbrev-completion` results are not the same as this capf gives (even with the two all-buffer variables set to nil).  Maybe capitalization transformation and length of candidate are the difference?  For least surprise, should probably be the same list `dabbrev-completion` would have returned (at least for the current buffer).

**Comment by jdtsmith** [comment] 2021-07-24 12:50
> However I could steal the explicit implementation. 
 Exactly :)

**Comment by minad** [comment] 2021-07-24 13:00
> Hmm, it's still picking up tons of words for me. Both of those variables are t but you do let-bind them. Looking closer, it appears dabbrev uses some internal mirrors of these variables (dabbrev--check-other-buffers etc.) and resets them to their global values periodically (dabbrev--reset-global-variables), defeating your dynamic bindings. I had to:

There was still a bug in the capf above, I correct it as follows:

~~~ elisp
    (let ((dabbrev-check-all-buffers nil)
          (dabbrev-check-other-buffers nil))
      (dabbrev--reset-global-variables))
~~~~

Please try the updated version.

> Some people have been praising fancy-dabbrev, which just auto-populates one match from dabbrev with a timer for immediate confirmation. This reminds me of the feature of company I still miss in corfu: if there is ever one and only one match, it removes the popup and pre-populates the buffer with just the (fontified) match, which can be Return confirmed (with no other confirmation possible):

Yes, we could do this. It may be a bit less annoying than showing the popup with only a single item. It should be pretty easy to implement this given that we already have an overlay available. Please open a separate issue. PRs are also welcome of course.

> I notice the actual dabbrev-completion results are not the same as this capf gives (even with the two all-buffer variables set to nil). Maybe capitalization transformation and length of candidate are the difference? For least surprise, should probably be the same list dabbrev-completion would have returned (at least for the current buffer).

Maybe, I am also a bit confused a bit by that. It could be that only the sorting is overwritten. dabbrev-completion overwrites only the cycle-sort-function, but corfu uses the display-sort-function. Otherwise one should check the difference between dabbrev-completion and my capf, but to me it does not look like there is a significant difference.

> That said, I do in fact like the setup that dabbrev-as-capf is "lightweight" and searches only this buffer, then if you want even more drawn from all(ish) buffers, reach for your Dabbrev-specific key (M-/ for me). Not sure how to defeat the variable mirrors to achieve that, but once I got only one buffer searching actually enabled, it was very fast for me, no delay whatsoever on ~4k-line Elisp files.

Yes, this makes sense. I also experimented with a heavier version which runs in an idle timer to fetch *all* possible abbreviations (by expanding ""), but this seems to be more messy. It seems using only the current buffer is fast enough for the capf.

**Comment by minad** [comment] 2021-10-17 10:47
UPDATE: This is my current library of extra capfs. I should package this up properly at some point and put it on MELPA.

~~~ elisp
;; -*- lexical-binding: t -*-

(require 'dabbrev)

;;;###autoload
(defun +file-completion-at-point-function ()
  "File name completion-at-point-function."
  (when-let (bounds (bounds-of-thing-at-point 'filename))
    (list (car bounds) (cdr bounds)
          'read-file-name-internal
          :exclusive 'no
          :annotation-function (lambda (_) " (File)"))))

;;;###autoload
(defun +dabbrev-completion-at-point-function ()
  (let ((dabbrev-check-all-buffers nil)
        (dabbrev-check-other-buffers nil))
    (dabbrev--reset-global-variables))
  (let ((abbrev (ignore-errors (dabbrev--abbrev-at-point))))
    (when (and abbrev (not (string-match-p "[ \t]" abbrev)))
      (pcase ;; Interruptible scanning
          (while-no-input
            (let ((inhibit-message t)
                  (message-log-max nil))
              (or (dabbrev--find-all-expansions
                   abbrev (dabbrev--ignore-case-p abbrev))
                  t)))
        ('nil (keyboard-quit))
        ('t nil)
        (words
         ;; Ignore completions which are too short
         (let ((min-len (+ 4 (length abbrev))))
           (setq words (seq-remove (lambda (x) (< (length x) min-len)) words)))
         (when words
           (let ((beg (progn (search-backward abbrev) (point)))
                 (end (progn (search-forward abbrev) (point))))
             (unless (string-match-p "\n" (buffer-substring beg end))
               (list beg end words
                     :exclusive 'no
                     :annotation-function (lambda (_) " (Dabbrev)"))))))))))

(autoload 'ispell-lookup-words "ispell")

;;;###autoload
(defun +ispell-completion-at-point-function ()
  (when-let* ((bounds (bounds-of-thing-at-point 'word))
              (table (with-demoted-errors
                         (let ((message-log-max nil)
                               (inhibit-message t))
                           (ispell-lookup-words
                            (format "*%s*"
                                    (buffer-substring-no-properties (car bounds) (cdr bounds))))))))
    (list (car bounds) (cdr bounds) table
          :exclusive 'no
          :annotation-function (lambda (_) " (Ispell)"))))

(defun +word-completion-at-point-function (words)
  (when-let (bounds (bounds-of-thing-at-point 'word))
    (list (car bounds) (cdr bounds) words
          :exclusive 'no
          :annotation-function (lambda (_) " (Words)"))))

(defvar +dict--words nil)
(defvar +dict-file "/etc/dictionaries-common/words")

;;;###autoload
(defun +dict-completion-at-point-function ()
  (+word-completion-at-point-function
   (or +dict--words
       (setq +dict--words
             (split-string (with-temp-buffer
                             (insert-file-contents-literally +dict-file)
                             (buffer-string))
                           "\n")))))

(provide '+capf)
~~~~

**Comment by jdtsmith** [comment] 2021-10-17 12:26
Thanks.  Do you use these with :exclusive no, or just at the end of the capfs list?

**Comment by minad** [comment] 2021-10-17 12:28
I put them at the end of the list, such that the major-mode specific capf always takes precedence. But I am currently considering adding a `corfu-try-all-capfs` option, which overrides exclusive, such that all of the capfs are always tried in order independent if they are exclusive or not.

**Comment by jdtsmith** [comment] 2021-10-17 12:46
Will be interested to see how that works out.  Currently struggling with eglot's CAPF (LSP with pylsp server): it's far too aggressive (completes in string, comments, at the beginning of words, replaces existing unrelated words in the buffer, etc.).  So adding yet more CAPFs to the pile will presumably not do good things.  I understand lsp-mode has similar issues.  They both have the pressing problem of not knowing _in advance of the capf call_ what the server will want to complete.  As the author of eglot said, the best possible case is completing symbols inside the same process itself (e.g. from obarray in elisp-mode).  Most modes have it much worse.  That said, I've got an unpublished mode with a similar issue and have worked around it in various ways, such that it works very well with corfu (and company).  So perhaps it's possible to make generic improvements.

**Comment by jdtsmith** [comment] 2021-10-17 14:23
Yes the server knows the position and full surrounding context.  The issue is that Emacs' CAPF mechanism presumes the CAPF knows _in advance_ what precise part of the buffer it will be completing.  Since the LSP client doesn't know this information until it hears back from the server, its only choice is to mark a large surrounding region and then attempt to fix it up after the fact.  In my mode, I "guess" a conservative region then use `bounds` to mark off the _actual_ completion region being considered after I hear back from the process.  But my completion is prefix-only, making this easier/more reliable.  Obviously I need my guessed region to be a super-set of the real region; if my guess is too parsimonious I get into trouble.  

Some generalization of CAPF to say "yes I can complete here, but I don't yet know which precise region I'll be completing, please stand by for that information" would be really valuable to LSP and other server/process-backed modes.   Emacs-lisp is in the happy place of knowing exactly what it wants to complete and having the dynamically up-to-date list of completions right at hand.

**Comment by jdtsmith** [comment] 2021-10-17 14:25
That said, I bet your `try-all-capfs` will be really useful for better-behaved/smaller completion spaces (LaTeX for example).

**Comment by ashton314** [comment] 2021-11-04 00:43
> Merging capfs is difficult/impossible in full generality though.

Just a thought—maybe this doesn't even make sense—I really don't know anything about the capf system: would it be possible to manually specify known groups of compatible capf systems? The ideal would be that everything just *works*, but alas, we live in a fallen world.

**Comment by minad** [comment] 2021-11-04 01:10
> would it be possible to manually specify known groups of compatible capf systems?

Yes of course, this is how one should implement this - the user has to
define such a merging multi-capf, which composes different sub-capfs.
One should still check compatibility of the capfs though.

There are three ways of composing capfs:

1. Merging, returning the union of all capf candidates (+)
2. Use capfs alternatively, first wins, exclusive=no (|)
3. Use capfs alternatively, first wins, exclusive=t (!)

By exclusive=no I mean that the capf in question determines immediately
if it applies and if not the next capf is tried. Furthermore the next
capf is also used if the first capf returns zero candidates. For
exclusive=t capfs, if the first capf applies, the next capf is never
tried, even if the first capf does not find any candidates. This
exclusive/non-exclusive distinction is a bit of an artifact and a result
of the capf implementation, where the completion is a two-stage process.
First the capf checks if it applies. If yes it returns a completion
table, if not it returns nil. In the second step Corfu asks the
completion table for the candidates.

Example capf composition:

(capf1 + capf2 + capf3) |
(capf4 + capf5) !
capf6

**Comment by jdtsmith** [comment] 2021-11-04 03:10
One issue I found with `exclusive 'no`: when enabled, CAPF will run a constant `try-completion` on each keyboard event with its own probe string, thanks to this gem in `completion--capf-wrapper`:

```elisp
          (and (eq 'no (plist-get (nthcdr 3 res) :exclusive))
               ;; FIXME: Here we'd need to decide whether there are
               ;; valid completions against the current text.  But this depends
               ;; on the actual completion UI (e.g. with the default completion
               ;; it depends on completion-style) ;-(
               ;; We approximate this result by checking whether prefix
               ;; completion might work, which means that non-prefix completion
               ;; will not work (or not right) for completion functions that
               ;; are non-exclusive.
               (null (try-completion (buffer-substring-no-properties
                                      (car res) (point))
                                     (nth 2 res)
                                     (plist-get (nthcdr 3 res) :predicate)))
```

**Comment by minad** [comment] 2021-11-04 07:59
@jdtsmith Corfu replaces the problematic code.

https://github.com/minad/corfu/blob/449d2b23f7fe0d0cb23ae4cc91b490ad1c29ba25/corfu.el#L982

**Comment by memeplex** [comment] 2021-11-17 07:20
It may be worth proposing the addition of some "missing" functions like these ones to core emacs. It's likely that the reason for their inexistence is that people have been busy writing backends for extensions for some years and cap was put aside.

**Comment by minad** [comment] 2021-11-17 07:28
> It may be worth proposing the addition of some "missing" functions like these ones to core emacs.

Sure, please do! Or even better directly propose patches upstream.

As you may have seen my completion packages (Vertico, Corfu) and also the complementary packages take some great care to adhere closely to existing Emacs facilities. So I am all for adding more base functionality to upstream. It should be noted however that the time it takes me to get a patch into Emacs itself takes me maybe ten times the time it takes me to implement this externally.

**Comment by minad** [comment] 2021-11-19 09:16
@memeplex See also https://www.reddit.com/r/emacs/comments/mhl92l/why_havent_companybackends_been_merged_into_capf/. This has been discussed often.

**Comment by minad** [comment] 2021-11-21 12:27
For now I collect the Completion At Point Extensions in https://github.com/minad/cape

**Closed** 2021-11-21 12:35 UTC
Labels: enhancement

**Comment by minad** [comment] 2021-11-22 18:48
Update: Cape provides a Company adapter and function to merge Capfs. See https://github.com/minad/cape#experimental-features.

**Comment by ashton314** [comment] 2021-11-22 20:04
I rejoice greatly at this! Vielen Dank Daniel!
