### ISSUE TITLE
Last typed char auto prepended to the following every typeing sometimes.

### ISSUE THREAD

**Issue by jilen** [minad/corfu#106] opened 2022-01-12 12:16 UTC
OS: MacOS
Emacs version: latest 28 with native compilation enabled
Corfu version: latest in melpa.

Sometimes when I type very fast (the completion backend be much slower than typing),  the last typed char will be prepend to the following type 

For example, I type very fast end with a char `a`. Then I press `b`, `c` , it becomes `ab`, `ac`
If I use `company-mode`  then everything is fine.

**Comment by minad** [comment] 2022-01-12 12:26
Do you really observe the following sequence of characters in the buffer?

1. "a"
2. "ab"
3. "ac" (the b deleted again?)

**Comment by jilen** [comment] 2022-01-12 12:37
No deletion. just prepend to the every typing.
I'll try to make a screenshot first

**Comment by jilen** [comment] 2022-01-12 12:40
"abac" but I only press the `bc` in the keyboard. `a` is prepend automatically even without  press  it

**Comment by minad** [comment] 2022-01-12 12:53
That's really odd. What is your precise setup, your settings, packages, etc.? Can you reproduce this with emacs -Q in a minimal setup? Corfu does not manipulate the buffer itself, it only observes the buffer content and updates the completion popup accordingly. Therefore this behavior must be caused by some unfortunate interaction of Corfu with some other package.

**Comment by jilen** [comment] 2022-01-12 12:58
Ok, let me try a minimal setup first. 
It could be a bug of emacs itself,  few months ago I had same issue with company-mode.
I'll close it for now. And reopen if I can indicates it is related to `corfu`

**Comment by jilen** [comment] 2022-01-19 07:03
Successfully reproduce it with  https://github.com/jilen/.emacs.d.
Seems happening when I am typing super fast (faster than the completion ui appearing). 
It is not very easy to reproduce, maybe occurs every few hours.

**Comment by minad** [comment] 2022-01-19 07:17
Please provide a minimal configuration. I doubt that I can do anything about this issue given your current description - "every few hours" and given your long init.el. Furthermore this is probably not a Corfu issue since Corfu does not interfere with the input in the buffer. It is more likely an issue of Emacs or maybe even an issue of the Mac port only. Please investigate further and narrow this down as good as you can. Otherwise I don't see anything actionable here and we can as well close the issue.

**Closed by minad** 2022-01-19 07:17 UTC

**Comment by minad** [comment] 2022-01-19 07:30
There is one thing I can help with if you tell me the completion backend you are using. Do you use lsp mode, eglot or some other capf? Then I could review if the backend itself could be causing this. In the ideal case you could reproduce it with elisp completion in a scratch buffer without any packages installed except Corfu.

**Comment by jilen** [comment] 2022-01-20 01:13
@minad I encounter this bug even while editing `sql` files.  And  only `cape` backends are available.
Do you have any idea how to debug  such cases ?
