### ISSUE TITLE
corfu & edebug

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#105] opened 2022-01-12 01:18 UTC
When using edebug to step through a buffer with Space (`edebug-step-mode`) with the minibuffer active, corfu auto-activates.

**Comment by minad** [comment] 2022-01-12 12:22
Please tell me the precise steps on how to reproduce this! I don't use edebug. I should probably get familiar with it at some point.

**Comment by minad** [comment] 2022-01-12 18:20
I can reproduce this. It seems that `edebug` is messing with `this-command` in weird ways. I could check for non-nil `edebug-mode` in `corfu--auto-post-command`, but my recommendation would rather be to disable `corfu-mode` in a buffer where the debugger is active.

**Comment by jdtsmith** [comment] 2022-01-12 18:53
Interesting.  I tried without my commit-predicate and found that wasn't the issue.  The problem with disabling the debugger is that you naturally go back and forth between edebugging and editing quite frequently.  

>> edebug is hard to live without once you learn it.
> I believe this won't happen in my case

Fascinating!  There are certain things that are hard for me to do without a debugger, like setting conditional breakpoints deep in some loop.  You can even do that (and update conditions) while debugging.  So I rarely step over one thing at a time (too fine grained as you say), but usually stop somewhere, sometimes on function entry, then use `h`ere to go to a deeper spot, add a condition, `g`o until the condition trips, examine some variables, etc.  Sadly the interface is pretty opaque/outdated; I had a very nice clean version in IDLWAVE (idlwave-shell-electric-debug) which I still miss.

**Comment by minad** [comment] 2022-01-12 19:02
Yes, it is not very convenient. But you could also add the `edebug-mode` check in an around advice in your config. I don't think we should add this except if we find a more general way to avoid triggering Corfu. We could consider adding a variable `corfu-auto-excluded-modes` which contains a list of variables of modes which must be nil for Corfu to trigger. Not sure if Company has something like this. But we should only add this if there are at least three such modes where one wants to disable Corfu otherwise it is not justified to add an extra configuration variable, only to fix a single mode.

**Comment by jdtsmith** [comment] 2022-01-12 19:50
Fully agree.  Hard coding things is a bad idea, as packages change and evolve.  So 10 years later you're saddled with a bunch of irrelevant cruft.  I've seen many such packages.  Key is to give users reasonably easy (and documented) access to rolling their own. 

Yes something like an optional `corfu-auto-predicate` to go along with the `corfu-commit-predicate` seems like the right approach.  I guess the idea would be to pop up if auto=t, AND the prefix is long enough (or overridden by company-prefix) AND corfu-auto-predicate (if any) says it's OK to.

**Comment by minad** [comment] 2022-01-12 20:01
> Yes something like an optional corfu-auto-predicate to go along with the corfu-commit-predicate seems like the right approach. 

Yeah, but predicates are also not that easy to configure. They require the user to write elisp, and then you could just go with an advice in this particular case. I looked into Company again and they don't have such special casing to exclude modes etc. They check if macros are defined however, which is reasonable (added in https://github.com/minad/corfu/commit/c08b9004a0e07a8fe29de2c26a3f76e16fa5b223). Adding a predicate only because of edebug is not justified. Therefore I close this issue. We can revisit if more use cases come up.

**Closed by minad** 2022-01-12 20:01 UTC

**Comment by minad** [comment] 2022-01-12 20:05
I should add, I also searched the Company issue tracker and my search didn't turn up anything relevant. This seems generally like a good guideline to see if issues are widespread or important, since many issues Company had also reappear here again if they concern edge cases which the baseline design does not handle.

**Comment by jdtsmith** [comment] 2022-01-12 20:18
I just tried the same recipe as above with company, and it doesn't pop-up.  I'm not sure how it avoids doing so.

**Comment by jdtsmith** [comment] 2022-01-12 20:20
> > corfu-commit-predicate seems like the right approach.
> They require the user to write elisp

Or more likely, copy elisp from the wiki...

**Comment by minad** [comment] 2022-01-12 20:25
> I just tried the same recipe as above with company, and it doesn't pop-up. I'm not sure how it avoids doing so. That would explain why you saw no issue.

Okay, if you figure out how they avoid this we can use a similar approach. This is what I meant by "general way" in https://github.com/minad/corfu/issues/105#issuecomment-1011360204.

**Comment by minad** [comment] 2022-01-12 20:25
> Or more likely, copy elisp from the wiki...

Which very often is a malpractice. I am all for sharing snippets. But I don't think copying snippets without understanding them is good.

**Comment by jdtsmith** [comment] 2022-01-12 20:36
The advice is trivial, so I'll go with that for now.  In case anyone finds this and is looking for a fix:

```elisp
(defun my/corfu--auto-post-command-advice ()
    (not edebug-mode))
(advice-add #'corfu--auto-post-command :before-while #'my/corfu--auto-post-command-advice)
```

**Comment by minad** [comment] 2022-01-12 20:43
I added more checks, which are also used by Company: See https://github.com/minad/corfu/commit/fef546f221a690c09c67dcca1a1217d6e3215907. Maybe this fixes the issue. I didn't try yet.
