### ISSUE TITLE
Laggy tab and return completion insertion

### ISSUE THREAD

**Issue by pushqrdx** [minad/corfu#48] opened 2021-08-08 18:53 UTC
The showing of the completion popup and accepting a completion both result in very noticeable input lag, in case of popup showing at least 30ms and for completion inserting 50+ms, note that i am not talking about the auto complete timer (the time before showing the pop), even if it's set to 0 the same lag exists

**Comment by minad** [comment] 2021-08-08 19:00
For me Corfu is quite fast. Is there something special about your setup/configuration? Please provide more information.

**Comment by pushqrdx** [comment] 2021-08-08 19:19
@minad nothing special i just tried in a clean emacs.d with nothing but corfu with following settings, input lag is quite big, using latest emacs 28

```lisp
(setq tab-always-indent 'complete
	  completion-cycle-threshold 3
	  corfu-auto-delay 0.0
	  corfu-quit-no-match t
	  corfu-cycle t                ;; Enable cycling for `corfu-next/previous'
	  corfu-auto-prefix 1
	  corfu-auto t                 ;; Enable auto completion
	  corfu-commit-predicate nil   ;; Do not commit selected candidates on next input
	  corfu-quit-at-boundary t     ;; Automatically quit at word boundary
	  corfu-quit-no-match t        ;; Automatically quit if there is no match
	  corfu-echo-documentation nil) ;; Do not show documentation in the echo area
(corfu-global-mode)
```

**Comment by minad** [comment] 2021-08-08 19:25
You want to use corfu-auto with corfu-auto-delay=0? This is an unsupported setting. Can you reproduce the problem with a realistic value, e.g., 0.1 or 0.2s? Furthermore corfu-auto-prefix=1 will be inefficient since many candidates are generated every time. In any case if you can capture a profile it would be appreciated to see the cost centers.

**Comment by pushqrdx** [comment] 2021-08-08 20:09
@minad even with the following config which is pretty vanilla, backspacing the last character before the popup menu closes has noticeable input lag, selecting candidate with return also takes at least 30+ms, i wonder how can i produce that profile you're asking about?

```lisp
(setq tab-always-indent 'complete)
(corfu-global-mode)
```

**Comment by minad** [comment] 2021-08-08 20:17
Take a look at profiler-start and profiler-report. Run profiler-start, trigger Corfu a few times and look at the reported profile. Maybe we can optimize a few hot spots, but I am doubtful. If you tab with a longer prefix the candidate generation should be fast. If you backspace then you will broaden the completion to more and more candidates and it will get slower as the prefix gets shorter.

**Comment by pushqrdx** [comment] 2021-08-08 20:20
@minad alright but backspacing while the popup is visible has no issues, it's the last backspace (deleting last char) before the popup closes that causes input lag, this also happens when submitting a completion so i suspect that the lag is causes by showing/destroying the childframe, i will come back with the profiles

**Comment by minad** [comment] 2021-08-08 20:24
I see. This could be. However Corfu does not destroy the child frame - it only hides it since destruction and creation is far too slow. Child frame hiding/showing could still be slow. In this case the problem is the Emacs display engine, your window manager, your X server or something else. Do you use pgtk? Maybe this improves the situation?

**Comment by pushqrdx** [comment] 2021-08-08 20:41
@minad i am on linux, xorg, compiz and i have no issues with emacs outside of corfu everything is pretty fast, i am also already using emacs 28 pgtk + native comp, here's one report where i just used corfu few times
```
         127  50% + command-execute
         102  40% + corfu--post-command
          10   3% + ...
           8   3% + jit-lock--antiblink-post-command
           7   2% + redisplay_internal (C function)
```
and here's another one where i just focused on triggering corfu to show the menu then backspace till it's hidden
```
          84  43% + command-execute
          84  43% + corfu--post-command
          13   6% + ...
          10   5% + timer-event-handler
```
as you can see it doesn't appear to be a redisplay issue, and most of the time is spent with post-command

**Comment by minad** [comment] 2021-08-08 20:43
Okay, you have to unfold the post command hook to see where the time is actually spent.

**Comment by pushqrdx** [comment] 2021-08-08 20:48
@minad whops, sorry didn't know that they are unfoldable
```
          85  80% - corfu--post-command
          85  80%  - corfu--update
          81  76%   - corfu--update-candidates
          81  76%    - corfu--recompute-candidates
          61  57%     - corfu--all-completions
          61  57%      - completion-all-completions
          61  57%       - completion--nth-completion
          61  57%        - completion--some
          61  57%         + #<compiled -0xd2f4afa5a39c3e2>
           8   7%       sort
           8   7%     + corfu--move-prefix-candidates-to-front
           4   3%     corfu--show-candidates
```

**Comment by minad** [comment] 2021-08-08 20:52
Thanks! Learning the Emacs profiler in the way ;)

As I suspected most of the time is spent in completion-all-completions, which is the candidate regeneration function. I am afraid we cannot speed this up.

There is only one thing which I will improve - corfu--move-prefix-candidates-to-front is unreasonably slow. I will replace this function with a faster function.

**Comment by minad** [comment] 2021-08-08 20:57
Sorting could also be improved. In Vertico I am using an optimized bucket sort, but not yet in Corfu since Corfu didn't make problems for me now. The benchmark where you backspace is not a realistic/important use case since as I described above the number of candidates will be unreasonably large due to the short prefix.

**Comment by pushqrdx** [comment] 2021-08-08 20:59
@minad the weird thing is that the input lag only occurs on popup show/remove as in before last character is backspaced or after i hit return, in between that i can see candidates being updated without having any lag.. out of curiosity i adviced `corfu--popup-show` to test out what would happen and sure the lag went away (even though completion of first candidate still works ofc)
```lisp
(advice-add 'corfu--popup-show :override 'ignore)
```

**Comment by minad** [comment] 2021-08-08 21:01
The last character is the most expensive one. If you advise corfu--popup-show to do nothing this means that the display engine is the problem. It may be hard to benchmark this latency issue but corfu--popup-show does not perform expensive work, besides calling into the Emacs display engine.

**Comment by pushqrdx** [comment] 2021-08-08 21:03
@minad but we saw that redisplay is barely touched so i wonder why this is happening still

**Comment by minad** [comment] 2021-08-08 21:24
I don't think the code which hides/shows the child frame is related to redisplay, this is more about communicating with the wm. The redisplay is responsible for redrawing, this is fast as expected since we are not redrawing much.

**Comment by pushqrdx** [comment] 2021-08-08 21:51
@minad after some tinkering i found the culprit, `corfu--popup-hide` is blocking input until it finishes that's why it results in input lag, if i advice it input lag on last + candidate accept is fixed, so perhaps defer hiding the popup to let emacs handle keypresses first

**Comment by minad** [comment] 2021-08-08 21:58
Oh this sounds like a good find. How would that look? Move the hiding into a run-at-time?

**Comment by minad** [comment] 2021-08-08 22:03
See https://github.com/minad/corfu/commit/7d9604d52e2f76c181f5091fd8eae9d5b74124ff. Does this fix your latency issue?

**Comment by pushqrdx** [comment] 2021-08-08 22:07
@minad no hiding it right away with 0 doesn't affect input lag, however i am experimenting with these 2 changes that seem to eliminate all input lag, even the occasional ones that happen during input filtering

first i just deferred `corfu--popup-hide` by wrapping the whole thing in a `run-with-idle-timer 0.1`, 
second i also wrapped `corfu--update` call in `corfu--post-comman` with a very small idle delay 0.005

Both of these eliminated input lag

**Comment by minad** [comment] 2021-08-08 22:10
This does not sound good. I think it would be okay to only defer hide and show popup, but I don't want to defer the entire update.

**Comment by minad** [comment] 2021-08-08 22:11
Also the hide delay seems large. And the usage of idle timers also doesn't sound good except if we make sure that only one is active at a time.

**Comment by pushqrdx** [comment] 2021-08-08 22:12
@minad without deferring the update you're blocking emacs's ability to handle keystrokes while the candidate filtering happens, which results in added latency, even a very small value like 0.005 is enough to give emacs a chance. Idk about using idle timer but the key is we need to give emacs a chance to handle a keystroke, otherwise you're blocking the ui

**Comment by minad** [comment] 2021-08-08 22:13
This is incorrect.  The Corfu candidate recomputation is already interruptible.

**Comment by minad** [comment] 2021-08-08 22:14
So if only popup hide/show is the issue we can additionally defer that. But the rest of the code should not be affected.

**Comment by pushqrdx** [comment] 2021-08-08 22:14
@minad then i wonder why wrapping `corfu-update` gets rid of candidate filtering input lag (that doesn't always happen but occasionally enough to be noticeable also), another thing in your diff if i use `run-at-time 0.005` instead of `0` the hide input lag is fixed

**Comment by minad** [comment] 2021-08-08 22:17
Hmm, maybe you are right and interruptible recomputation is orthogonal to deferring the computation.

**Comment by pushqrdx** [comment] 2021-08-08 22:23
deferring `corfu--update` even with 0.005 (but not just 0) surely gets rid of candidate filtering input lag, that along with the deferred popup-hiding (0.005) made the input so much more responsive, as in i can't notice any input lag, which i usually can notice down to ~8-10ms

**Comment by minad** [comment] 2021-08-08 22:32
Okay, so just to understand this precisely - you care about the lag of the letter you entered? Since Emacs is unable to draw the popup quickly enough you want to defer the popup such that the letter appears immediately, and then the popup can open/update a little bit later? Unfortunately the fix you are describing is not very clean. I want something reliable which also transfers to my Vertico UI. Deferring corfu--update/vertico--exhibit takes the recomputation out of the post-command-hook order, which is a problem in combination with my Consult package, which relies on the candidates being available at a certain point in a post-command-hook. Of course I could also defer the preview update, but these fixes are not isolated. Another potential fix that has been discussed previously is to `redisplay` just before the candidate recomputation (see https://github.com/minad/vertico/issues/89), but there the issue is much more severe since thanks to Tramp the input lag can be very long.

**Comment by pushqrdx** [comment] 2021-08-08 22:40
@minad 
> you care about the lag of the letter you entered?
yes ofcourse, when i press a key and it displays 30+ms later the overall experience is pretty jarring, you expect a key to appear almost instantly when you type it, popup showing/hiding can wait but not keypresses. Same goes during the the actual completion process, you won't feel lag if the candidate filter is a few milliseconds behind but you will feel it if the display of the keys is behind, Unfortunately i am not sure how else you can cleanly make that happen and retain your integration with vertico..

**Comment by minad** [comment] 2021-08-08 22:52
Okay, thanks. Now I understand this better. I agree with you about this. But somehow for me these things are coupled now, or let's say I accepted that the letter display is as slow as the candidate display. But this does not mean that we should not improve this, it would be great if we could and also solve https://github.com/minad/vertico/issues/89 on the go. I am sorry for broadening the issue, but in the long term this will help me with maintenance. The fix goes along these lines: 1. Always defer the UI updates, the entire corfu--post-command-hook, corfu--popup-hide and vertico--exhibit. Refactor Consult preview such that it is triggered by the UI, instead of doing its own thing via its own post-command-hook. This require changes to the UI integration code.

**Comment by pushqrdx** [comment] 2021-08-08 23:02
@minad indeed, no problem, i understand the need to cleanly tackle this issue though i am sure the reward is worth it. I'm not using Vertico but i'll try to tinker around so that perhaps i can further assist.

**Comment by minad** [comment] 2021-08-08 23:05
Out of interest, what do you use?

**Comment by pushqrdx** [comment] 2021-08-08 23:06
@minad icomplete + fido + vertical mode

```lisp
  (fido-mode)
  (icomplete-vertical-mode)
  (setq completion-show-help nil
	completion-auto-help nil
	icomplete-compute-delay 0.0)
  (rc/bind-keys!
   :keymaps (icomplete-minibuffer-map)
   ("TAB" . 'icomplete-force-complete))
```

**Comment by minad** [comment] 2021-08-08 23:09
Oh interesting, why is that? Icomplete+flex is much slower than Vertico - in particular if you care about latency. I am not trying to convert you here of course, but I still find it interesting to know why users prefer one over the other.

**Comment by pushqrdx** [comment] 2021-08-08 23:14
@minad fido-mode (which enables icomplete with flex plus few other things) never added any noticeable input lag for me but ofc you have to set `compute-delay` otherwise it's slow. As to the reason, nothing really, i just prefer built-in whenever they're good enough, all my emacs config is 90% built-in functionality with few tweaks, even that `rc/bind-keys!` is a thin macro around `define-key`

**Comment by minad** [comment] 2021-08-08 23:59
Thanks. I agree that it is not unreasonable to use built-ins if they are good enough. This is of course a matter of preference and depends on many details.

**Comment by pushqrdx** [comment] 2021-08-09 00:06
@minad with all of that being said if i can't get marginalia to work with built-in vertical mode + fido (readme says it works with icomplete but it doesn't for some reason, maybe needs vertical-mode the external package) i will just use Vertico, i just found out marginalia and i want some of this fanciness

**Comment by minad** [comment] 2021-08-09 00:23
I just tested icomplete-vertical-mode on Emacs 28 and it works as expected with Marginalia (I contributed part of the patch to Icomplete, which added annotations/affixations there). Overall the difference between Icomplete-vertical and Vertico is not huge. Both are small packages. Vertico has faster sorting (but only if you don't use flex, since flex uses its own sorting function) and a few other useful features and an improved interaction.

If you want to buy in to the full fanciness, install Vertico, Marginalia, Orderless, Consult and Embark. But then you cannot uphold your principle of sticking to built-ins ;)

**Comment by minad** [comment] 2021-08-09 01:14
@pushqrdx I looked at the vertico latency issue again and there I have the issue fixed already using redisplay, see https://github.com/minad/vertico/blob/be853e8ef60bf255ea4a5099805eb7492fcb0881/vertico.el#L318. Can you please check if a redisplay right before the recomputation fixes the issue in Corfu too?

**Comment by pushqrdx** [comment] 2021-08-09 01:34
@minad where should i plug that line?

**Comment by pushqrdx** [comment] 2021-08-09 02:00
i think we're close to something with redisplay, it almost got rid of all input lag except that one before backspacing last character

**Comment by pushqrdx** [comment] 2021-08-09 02:39
here's a test so we can get to the bottom of that last backspace issue, in an elisp file type these lines
```lisp
eeeeeeeeeeeeeeeeeeee
allout-auto-activati|
```
now with the cursor at | hold backspace till you start backspacing the `eee` you can see that the cursor at a consistent speed.. now repeat that but with corfu's popup open and once it gets to the last `a` emacs will input lag resulting in cursor delete multiple characters at once from the `eee` line

**Comment by minad** [comment] 2021-08-09 04:50
Ok, I pushed an update. Please check it. I wonder why it doesn't get rid of the backspace lag.

**Comment by pushqrdx** [comment] 2021-08-09 06:55
@minad yup this is exactly what i tried when you suggested using redisplay, a very big improvement already except for last char lag, it's confusing what's causing it, something with teardown maybe

**Comment by minad** [comment] 2021-08-09 07:04
Great. The redisplay in recompute is principled, it makes sense to have this there - similar to Vertico. The redisplay before the teardown is a bit more adhoc and unexpected.

I think the lag for the last character can be avoided if no recomputation is performed for an empty input string.

https://github.com/minad/corfu/blob/dcb299905721857d19ef741a246b7149026de8c1/corfu.el#L664

But recomputation already happens earlier:

https://github.com/minad/corfu/blob/dcb299905721857d19ef741a246b7149026de8c1/corfu.el#L655

**Comment by minad** [comment] 2021-08-09 07:11
Please try https://github.com/minad/corfu/commit/92c5ad1543ddd6c12fdaeee4cbb3eeaaa5860049.

**Comment by pushqrdx** [comment] 2021-08-09 17:15
@minad absolutely wonderful, with that one last char input lag is gone, candidate accept lag is gone, and i can't feel any input lag during candidate filtering. 
However since we're squashing all input lag, there's only one remaining and it's pretty weird, if you tab a candidate that doesn't exist (so that it displays `no match` in the minibuffer) subsequent 1 key press has a very noticeable input lag ~25-30ms

**Comment by pushqrdx** [comment] 2021-08-09 17:22
edited comment above as i discovered 1 more scenario with lag

**Closed** 2021-08-09 17:21 UTC

**Comment by minad** [comment] 2021-08-09 17:23
Okay, I merged the no empty recomputation branch. You can experiment with further `redisplays` and I can add them if it does not feel too much off. Please open new issues for these cases with proposals where the `redisplay` should be. But I consider the issue to be resolved mostly now, so I closed this issue here.

**Comment by pushqrdx** [comment] 2021-08-09 17:25
@minad makes sense, i don't have corfu-auto anyways so it's almost fixed for me too, and the scenario where first char after `no matches` lags is bareable, since you don't run into it that much anyways. overall completions now feel way more responsive!
