### ISSUE TITLE
make-frame is causing significant input lag for the very first few keystrokes.

### ISSUE THREAD

**Issue by pushqrdx** [minad/corfu#361] opened 2023-08-25 15:48 UTC
I have noticed that whenever the candidate list is shown for the very first time after launching Emacs, it causes a big lag spike with input latency of around ~50ms for about ~8-10 keystrokes for a total of ~400-500ms before dropping _and staying at_ the usual ~1ms mark for the rest of the emacs session. I have tracked it down to exactly `make-frame` in the `corfu--make-frame` function. Removing the `make-frame` call gets rid of the problem. This input latency can be felt if you start typing really fast as you can see the cursor lag behind. Once the initial spike goes away everything stays smooth. 

This can be observed anywhere `corfu` is enabled, I have tested in `elisp` buffers, In the read expression mini buffer, and with `lsp-mode`, all with equally similar latency.

I thought if it only happens once, I should be able to just call `make-frame` on startup in order for whatever initial setup that causes this lag to occur before user input, but surprisingly that didn't have the intended effect. For some reason only after `corfu` makes the initial calls to `make-frame` that it no longer causes that lag in subsequent uses. So, I must be missing something.

**Comment by minad** [comment] 2023-08-25 16:07
Hi! Thanks for the report. As a matter of fact we have to call `make-frame` at least once. It is of course not great if the very first stroke lags, but it is not too bad if the problem goes away afterwards. I doubt that we can do anything about this in Corfu. The slow frame creation must be fixed on a different level in Emacs itself. From my experience, the Emacs child frame API is hard to use, inefficient and prone to flicker (see for example #357). For these reasons I don't see anything actionable here, but feel free to prove me wrong by [contributing patches](https://github.com/minad/corfu#contributions) which improve the situation.

**Closed by minad** 2023-08-25 16:07 UTC

**Comment by pushqrdx** [comment] 2023-08-25 16:25
@minad Oh I didn't know it's a known issue. Makes sense.

> As a matter of fact we have to call make-frame at least once

Can you please clarify this part? What about my idea to somehow do this behind the scenes maybe during init to avoid it happening during typing? If I wanted to correctly go about it, what should I try? I have tried manually calling `(corfu--make-frame corfu--frame 0 0 0 0 (current-buffer))` but that didn't seem to help.

**Comment by minad** [comment] 2023-08-25 16:37
We could try to create the frame earlier in the background, but I don't think that the added complexity is justified. If frame creation is so slow to cause noticeable latency, something is wrong in the display stack and the root cause should be fixed. In other words I want to keep the lazy frame creation code. 

I do not want to try to work around all kinds of obstacles at the level of Corfu. Also note that `corfu--make-frame` sometimes has to recreate the frame, which can happen when switching between different parent frames. It could also happen that the frame was deleted, either by some side effect or by some user action.

There is still a possibility that we are doing something wrong in `corfu--make-frame`. Maybe some of the `corfu--frame-parameters` are expensive, maybe the parameters we specify to `make-frame` are somewhat off or maybe the order of API calls is inefficient. So far I could not figure out performance improvements to `corfu--make-frame`. You could take a look at [eldoc-box](https://github.com/casouri/eldoc-box) if the child frame code there is more efficient.

**Comment by pushqrdx** [comment] 2023-08-25 16:55
@minad that makes sense, and if `make-frame` itself is slow it shouldn't be worked around in `corfu` especially that the problem is just a slight annoyance, I have had no other performance problems with `corfu` and I think it's very fast, I have measured the added input latency by `corfu` and it's very minimal, sometimes almost non-existent which makes me happy as I am generally very sensitive to input lag.

**Comment by minad** [comment] 2023-08-25 17:03
Yes, Corfu doesn't have big latency problems. Of course the backend has a big impact. However the Emacs child frames are quite unsatisfying. The flicker sometimes during redisplay, resizing or movement.

**Comment by pushqrdx** [comment] 2023-08-25 17:06
@minad luckily, I am not experiencing any flickering with `corfu`, probably because of double buffering.

**Comment by pushqrdx** [comment] 2023-08-25 17:15
@minad I just tested `eldoc-box` and it has the same issue exact issue with the same latency.
