### ISSUE TITLE
corfu pop-up frames have wrong face heights

### ISSUE THREAD

**Issue by ArsenArsen** [minad/corfu#315] opened 2023-04-04 11:23 UTC
Hi!

When playing with frame-local face attributes, I noticed that Corfu behaved strangely (namely, it used one face size to create and another to populate completion frames).

You can replicate this by running `(set-face-attribute 'default (selected-frame) :height 150)` and trying to complete in that frame (change 150 to some value significantly different from your usual face height).

I've added this bit of code to copy the height from the old frame to the new, and it appears to have helped the case, though I'm uncertain if it's the right fix: https://github.com/ArsenArsen/corfu/commit/d2e4cf48127ecdec8becb9d298f943d0ba5beeca

Before:
![image](https://user-images.githubusercontent.com/7805050/229776492-8e0b25d5-6e35-4304-a4cd-bbde94284a45.png)

After:
![image](https://user-images.githubusercontent.com/7805050/229776602-da2d31a2-364c-498a-87fa-caf21d81bfe5.png)

Thanks in advance, have a lovely day.

**Comment by minad** [comment] 2023-04-04 13:44
Seems like a duplicate of #304.

**Closed by minad** 2023-04-04 13:44 UTC

**Comment by ArsenArsen** [comment] 2023-04-04 16:48
Ah - my bad, I missed that one.

This is indeed the same report, but I believe the right fix is to copy the face attributes from the parent to the new frame when setting it up, like in the patch I linked to above.

My use-case intentionally only adjusted the size of fonts in one frame (the one I was presenting in) while keeping others (e.g. the one that held my email client) unchanged, so the font sizes were intentionally different.

**Comment by minad** [comment] 2023-04-04 17:06
> This is indeed the same report, but I believe the right fix is to copy the face attributes from the parent to the new frame when setting it up, like in the patch I linked to above.

No, I want to keep things simple. It is unclear where to stop with copying attributes. See also #286 where one has to copy yet another attribute. If you use text scaling it will be inherited by Corfu. This probably works too for your use case?

**Comment by ArsenArsen** [comment] 2023-04-04 22:13
Hm, this does seem a bit inelegant, to be fair.

The thing about scale is that it is buffer-specific, rather than being frame-specific, but if you believe that to be a better solution, I can live with it.

But, on that thought, maybe copying all attributes is also a reasonable thing to do?
