### ISSUE TITLE
Annotations occasionally stay on completion

### ISSUE THREAD

**Issue by YotamGurfinkel** [minad/corfu#184] opened 2022-06-02 20:11 UTC
When using corfu with lsp-java I noticed the types/package names get inserted as part of the completion when hitting enter, flashing for half a second, then disappearing
For example
![image](https://user-images.githubusercontent.com/47272502/171728909-81ad5a78-454d-48b3-9b81-ee757b88ad54.png)

when completing "List", the "java.util" is a part of the completion and when quick typing and completing this can happen
![image](https://user-images.githubusercontent.com/47272502/171729067-834494c8-ba4f-4671-91f9-2d4b6d683ef6.png)

in comparison, when completing with company the type also appears after the dash separator, but it doesn't flash on completion
![image](https://user-images.githubusercontent.com/47272502/171729500-d48fd842-2d92-4249-b86e-4d998302f1f9.png)

**Comment by minad** [comment] 2022-06-02 20:25
I think the package name `- java.util` should not be part of the completion candidate. Please ask on the lsp-mode issue tracker about this issue. Maybe Corfu could be changed to improve the behavior, such that the flashing goes away. But it would be better to fix the underlying problem. It seems that lsp-mode attempts to remove the package suffix in the `:exit-function`? Maybe the lsp-mode maintainer @yyoncho can be of help?

**Comment by YotamGurfinkel** [comment] 2022-06-02 21:20
Correct. There isn't any flashing on company's side, in Corfu the cursor jumps to the end of the line then goes back quickly. So I'm guessing it's intentional on lsp-mode's side that packages names are part of a completion candidate. Is this worth looking into? @minad

**Comment by yyoncho** [comment] 2022-06-02 21:25
Are you using latest and greatest lsp-mode with no patches applied? Cause I was recently recommending a patch to avoid different issue that may trigger the described scenario.

**Comment by YotamGurfinkel** [comment] 2022-06-02 21:34
I am using the latest lsp-mode, removed all patches, can you maybe provide me with a link to the patch you recommended so I could try it?

**Comment by YotamGurfinkel** [comment] 2022-06-02 21:47
Oh.. got it. At least it doesn't happen at most times I guess so it's bearable atm. Maybe there's some workaround that can be done on Corfu's side..

**Comment by minad** [comment] 2022-06-02 22:03
I am not sure I understand, but it seems that the lag is due to some lsp-mode behavior and should be fixed there? Or is there something Corfu could do to work around the issue?

@yyoncho Is there a chance that you test also against Corfu from time to time since Corfu seems to gain more popularity? Overall it is simpler than Company, which makes it a good package to test against.

**Comment by yyoncho** [comment] 2022-06-03 11:41
@minad I would say that it will help if corfu eliminates everything that happens between inserting the candidate and calling the exit-function (I had a brief look in corfu code and it seems like there is room for improvement in that direction, although I might be wrong).

IMO having 0.5 seconds delay is quite a lot and I guess maybe the issue is that corfu lets emacs event loop to process other events which will result in this behavior. This is the only explanation I can come with.

**Closed** 2022-06-03 11:58 UTC

**Comment by minad** [comment] 2022-06-03 11:59
I defer the popup hiding a little bit. But there is not much else we can do.

**Comment by YotamGurfinkel** [comment] 2022-06-03 12:18
Don't see the problem now. Maybe this pretty much fixed it, or close to
