### ISSUE TITLE
Suggestion: any self-insert command during completion first de-selects and restores text

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#40] opened 2021-07-19 03:51 UTC
One of the most amazing things about corfu is that after the frame pops up, you can _refine_ your search using fancy completion styles like orderless (_spaces and all_).  This make in-buffer completion "feel" more like mini-buffer completion.  But once you have arrowed down to select a candidate (giving a blue highlight), any additional typing retains the text of the current selected candidate and appends to it.  Far preferable would be to _revert_ to whatever was actually typed in since the popup came up.  I.e _only_ [Ret]=`corfu-insert` could insert a candidate in a permanent manner (remaining after popup-hide). 

Here's a typical scenario:

1. I start a completion, which has many pages of candidates but I'm not sure how many.
2. I start scrolling down with arrow key, and quickly notice there are way too many pages to find what I'm looking for.  Some random candidate has now replaced my text. 
3. I think of an additional bit of a search I can include to narrow it down, so I start typing that.  
3. corfu retains the text of whatever candidate was selected and appends my text to it :(.  No match. 

If in the last step corfu had said "I see you are typing yet more match info, I'd better remove this temporary possible candidate I had put there first to let you continue refining" that would have worked just as well as it does when you didn't yet select a candidate.

Thanks for this package.  Having fun considering a post-company lifestyle...

**Comment by minad** [comment] 2021-07-19 20:36
The current behavior is intentional. I call this behavior auto commit, since it allows you to continue to type the expression you were going to type without the unnecessary RET. Therefore I disagree that the behavior you propose would be far more useful.

However it should be easy to add a customization option `corfu-auto-commit` which is checked in the corfu pre command hook. If disabled, Corfu could reset the selected candidate instead of commiting, as you propose.

**Comment by jdtsmith** [comment] 2021-07-19 20:49
I see.  In fact I've since found places where this behavior is indeed useful (in Elisp) even for refining selection, for example selecting one candidate with an arrow, then extending that string for a further search based on the same stem.  

I'm intrigued by the notion of "deselect the candidate".  How does one accomplish that conveniently (other than arrowing all the way up to the top of the list)? Maybe a single escape could arrange to deselect?  Best of both worlds?

**Comment by minad** [comment] 2021-07-19 20:57
Jump to the beginning and then press up once should get you back, I think. You can also do it in a single command of course, but I don't think this is offered ootb.

But I think it would be good to have auto commit configurable since it is somehow a non trivial special behavior. Corfu already allows to customize the quitting behavior.

**Comment by jdtsmith** [comment] 2021-07-19 22:00
Sounds good.  Would also be great to have a binding or bindable command for "clear selection".  I tried binding `("S-<up>" . (lambda () (interactive) (corfu-first) (corfu-previous))))` but no luck.   BTW, since there is always one "implicit" selection (namely, the first) even when nothing is selected, it might make sense to highlight the first match in that case, perhaps with a more muted highlight color.

**Comment by minad** [comment] 2021-07-20 23:55
> Would also be great to have a binding or bindable command for "clear selection". 

You can execute `corfu-first` twice (remapping of beginning-of-buffer). I don't think there is a need for a separate keybinding. Like in Vertico, I try to avoid adding bindings beyond some basic remappings.

~~~ elisp
(defun corfu-goto-prompt ()
  (interactive)
  (corfu-first)
  (corfu-first))

(define-key corfu-map "\M-s" #'corfu-goto-prompt)
~~~ 

> Also, I notice that if you have spaces in your search text, adding more text doesn't cause auto-commit, which is a surprising difference.

I cannot reproduce this. The space does not make a difference.

**Comment by minad** [comment] 2021-07-21 00:44
To resolve the issue there are a few possibilities of varying flexibility and I have to think a bit more about this.

1. Generalize `corfu--continue-p` to a configurable `corfu-continue-function`. The function can return `reset`, `continue` or `commit`. The default continue function is configured via some additional configuration variables.
 
2. Generalize `corfu--continue-p` to a configurable `corfu-continue-predicate`. This predicate will be checked to determine if the popup should be kept alive. Add a configurable `corfu-commit-predicate`. This predicate will be checked when a candidate has been selected and when the `corfu-continue-predicate` failed. If the commit predicate fails, the selected candidate will be reset.

**Comment by jdtsmith** [comment] 2021-07-21 01:19
> I cannot reproduce this. The space does not make a difference.

I can't reproduce either, actually.  If it recurs I will see if I can figure out why.

**Closed** 2021-07-21 12:47 UTC

**Comment by jdtsmith** [comment] 2021-07-21 17:56
Great new config option, thanks.

**Comment by minad** [comment] 2021-07-21 18:17
For completeness - the idea of the commit predicate is that one can check the inserted character and only return to the prompt if a certain key is pressed. For example SPC would work pretty well with orderless. For all other characters, e.g., punctuation characters, auto-commit could still be enabled.

**Comment by jdtsmith** [comment] 2021-07-21 21:11
Thanks for this suggestion.  I tried this and ended up with:

```elisp
(setq corfu-commit-predicate
	(lambda ()
	  (not (seq-contains-p '([? ] [S-up]) (this-command-keys-vector)))))
```

which works well: space continues refining even when selected, Shift-<up> provides another (non-inserting) way to "de-select", and any other event "auto-commits".
