### ISSUE TITLE
delay in pgtk emacs

### ISSUE THREAD

**Issue by p00f** [minad/corfu#316] opened 2023-04-06 23:06 UTC
When I use pgtk emacs, there's a noticeable latency between typing the trigger character `.` and the popup appearing, which does not happen in terminal emacs with https://codeberg.org/akib/emacs-corfu-terminal

https://user-images.githubusercontent.com/36493671/230507599-cc350145-4881-41c1-b73b-7e58547c1a85.mp4

Profiler report in pgtk (`profiler-start`, press trigger, `profiler-stop`)

[profiler-report-gui.txt](https://github.com/minad/corfu/files/11174950/profiler-report-gui.txt)

Profiler report in terminal
[profiler-report-terminal.txt](https://github.com/minad/corfu/files/11174951/profiler-report-terminal.txt)

**Comment by minad** [comment] 2023-04-06 23:11
This is likely a duplicate of #307. Please check it out, in particular the tip about `(setq-default pgtk-wait-for-event-timeout 0)`. Pgtk doesn't seem to be recommended generally, since the X11 display is supposedly better. I use the X11/Lucid toolkit for a lightweight UI.

**Comment by p00f** [comment] 2023-04-06 23:31
I have to use pgtk as I use wayland, and `(setq-default pgtk-wait-for-event-timeout 0)` doesn't help in my case. Thanks for looking though!

**Comment by minad** [comment] 2023-04-06 23:37
Okay, then there is probably nothing we can do in order to improve this. Do you use other child frame packages? You could try https://github.com/tumashu/posframe, write some code which creates a popup an check if it also leads to a similar delay.

**Comment by p00f** [comment] 2023-04-06 23:42
I use eldoc-box, setting `eldoc-idle-delay` to `0.0` makes it instant:

https://user-images.githubusercontent.com/36493671/230513027-2b5d5fdb-d84a-45e8-b887-a5281fb6c153.mp4

**Comment by minad** [comment] 2023-04-06 23:58
I assume you use Emacs 29 or 30? If you use Emacs 28, Corfu contains some messy code which tries to workaround redisplay bugs.

https://github.com/minad/corfu/blob/85bb1338fd13e061c6c4f2c6d51ef51a6eba3d1a/corfu.el#L451-L465

But this code should be disabled if you install/recompile Corfu on Emacs 29. 

Then I found another difference to eldoc-box. There is an inhibit-redisplay in Corfu, which you could try to comment out.

https://github.com/minad/corfu/blob/85bb1338fd13e061c6c4f2c6d51ef51a6eba3d1a/corfu.el#L402

Maybe @casouri has some further insight on what we could improve about the Corfu child frame code.

**Comment by casouri** [comment] 2023-04-07 00:09
Maybe instrument the code (add some `message` calls) and see if corfu is taking the code path which deletes and recreates the childframe every time?

**Comment by minad** [comment] 2023-04-07 00:15
@casouri Thanks, that's a good point. This doesn't happen on my setup. I am sure I would have noticed. But maybe something is different with pgtk. This is the condition used by Corfu:

https://github.com/minad/corfu/blob/85bb1338fd13e061c6c4f2c6d51ef51a6eba3d1a/corfu.el#L407-L411

Did you also notice the issue with the dead window on Emacs 29? Besides that, Corfu could do better if the frame parent changed as you do in eldoc-box, but this shouldn't happen here?!

**Comment by casouri** [comment] 2023-04-07 00:28
> Did you also notice the issue with the dead window on Emacs 29?

No. Eldoc-box uses `frame-selected-window` and so far there haven't been any issue. I see that corfu uses the root window. If there are multiple windows, the root window would be an internal window, which makes `window-live-p` return nil. Maybe the window is not "dead", but rather somehow there are more than one window in the childframe?

**Comment by minad** [comment] 2023-04-07 00:31
@casouri Multiple windows shouldn't happen in the Corfu child frame, I suppose. But probably `frame-selected-window` is a safer solution.

**Comment by p00f** [comment] 2023-04-07 00:51
I changed it to
```elisp
    (if (and (frame-live-p frame)
                 (eq (frame-parent frame) parent)
                 ;; XXX HACK: It seems the frame can be alive but have a dead window?
                 ;; Is this a Emacs 29 regression?
                 (window-live-p (frame-root-window frame)))
        (message "--- CORFU: CONDITION WAS TRUE ---")
      (message "--- CORFU: CONDITION WAS FALSE ---")
      (when frame (delete-frame frame))
      (setq frame (make-frame
                   `((parent-frame . ,parent)
                     (minibuffer . ,(minibuffer-window parent))
                     (width . 0) (height . 0) (visibility . nil)
                     ;; Set `internal-border-width' for Emacs 27
                     (internal-border-width
                      . ,(alist-get 'child-frame-border-width corfu--frame-parameters))
                     ,@corfu--frame-parameters))))
```

and I get `--- CORFU: CONDITION WAS FALSE ---` once and true after that

**Comment by minad** [comment] 2023-04-07 08:29
I made some more changes which may help, but I am unsure. See https://github.com/minad/corfu/commit/c8ad7bd53959786d2c52544d22239b57465fd4e0. I don't understand what is causing such a significant delay. Did you try commenting out the `inhibit-redisplay` from https://github.com/minad/corfu/issues/316#issuecomment-1499771109?

**Comment by p00f** [comment] 2023-04-07 08:45
It helps but not a lot, I've switched to terminal emacs for the time being (only using gui emacs for org-mode)

**Comment by minad** [comment] 2023-04-07 08:55
Okay, I am afraid I cannot help you with this one. The best bet would be to copy code from @casouri's eldoc-box and check if that improves this situation. Hopefully this is the case. Then one could slowly change the code such that it looks like the current Corfu code, to find where the difference is coming from.

**Closed by minad** 2023-04-07 08:55 UTC
