### ISSUE TITLE
LSP-mode header completion issue

### ISSUE THREAD

**Issue by drcxd** [minad/corfu#176] opened 2022-05-28 09:32 UTC
I am switching from company to corfu recently, and I found an issue about header completion.

Here is what I got from corfu:

![image](https://user-images.githubusercontent.com/24535087/170818869-04201fe6-45bc-46b1-bb7e-d74616058548.png)

This is what I got from company:

![image](https://user-images.githubusercontent.com/24535087/170818934-fa5925da-8dcc-4a4a-bbe5-c48bcd1a4044.png)

More detailed observation is that after I typed `#include "`, the completion list has already popped up, and the header files start with character A appear at the beginning of the list. After I type more characters, the list does not update itself with the additional characters. If I press `C-g` to cancel the pop up completion list before I type anything, and then I type `V`, the completion list is populated with header files start with character V. However, no matter what I type afterwards, the list is not updated properly.

My corfu configuration is copied from the wiki page.
```
(setq lsp-completion-provider :none)
(defun corfu-lsp-setup ()
  (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
        '(orderless)))
(add-hook 'lsp-completion-mode-hook #'corfu-lsp-setup)
```

Could this behavior be fixed? Or, does it need a fix?

**Comment by minad** [comment] 2022-05-28 09:51
It seems that your `corfu-lsp-setup` is for some reason not effective. Orderless does not seem to be used here, but instead the passthrough filter of lsp-mode is still used, such that no filtering happens. Did the hook run? Is the `completion-category-defaults` variable updated properly? It must contain the entry `(lsp-capf (styles orderless))`. Please check the global value of the variable and the buffer-local value of the variable in the buffer where you use lsp. Closing since this is probably a misconfiguration.

**Closed by minad** 2022-05-28 09:51 UTC

**Comment by minad** [comment] 2022-05-28 09:53
As a sledgehammer method you could also run this in the buffer where lsp is used:

~~~ elisp
(setq-local completion-category-defaults nil
            completion-category-overrides nil
            completion-styles '(orderless))
~~~

Make sure that you run this *after* activating lsp-mode since lsp-mode messes with these settings.

**Comment by drcxd** [comment] 2022-05-28 09:57
I checked all the three variables in the buffer, their values are:
```
completion-category-defaults is a variable defined in ‘minibuffer.el’.

Its value is ((lsp-capf (styles orderless)))
Local in buffer MoveableController.hh; global value is nil
```
```
completion-category-overrides is a variable defined in ‘minibuffer.el’.

Its value is ((file (styles partial-completion)))
Original value was nil
```
```
completion-styles is a variable defined in ‘minibuffer.el’.

Its value is (orderless basic)
Original value was 
(basic partial-completion emacs22)
```

**Comment by minad** [comment] 2022-05-28 10:01
Okay, good! Is the issue specific to file completion only or also to completion of variable names etc?

**Comment by drcxd** [comment] 2022-05-28 10:09
I guess this issue happens also in other situations:
![image](https://user-images.githubusercontent.com/24535087/170820772-8325ffdb-ea01-4654-b4b1-92feed9010d6.png)
I got the pop up after I typed `->` and then after I typed `SetPo`, it only highlight that entry but did not discard the first one.
The value of `completion-at-point-functions` is:
```
completion-at-point-functions is a variable defined in ‘minibuffer.el’.

Its value is (lsp-completion-at-point)
Local in buffer MoveableController.cc; global value is 
(cape-dabbrev cape-file #f(compiled-function
                           ()
                           #<bytecode -0x810eb1b4bb5a4eb>)
              tags-completion-at-point-function)
```

**Comment by minad** [comment] 2022-05-28 10:16
> I guess this issue happens also in other situations:

Okay, good. This means that filtering in general does not work properly as I already wrote in https://github.com/minad/corfu/issues/176#issuecomment-1140224429 and we don't have some deeper issue here. 

Unfortunately I don't know why this happens. Are you using sufficiently new versions of all involved packages? You can try to reproduce the issue with emacs -Q (Emacs 28, newest versions of corfu and lsp-mode). You can also try flex instead of orderless as described in the wiki.

**Comment by minad** [comment] 2022-05-28 10:21
This issue could occur for example, if you use a very old version of lsp-mode from before https://github.com/emacs-lsp/lsp-mode/commit/1ece3b81ad10d1b10a2c73c6617b4426e673cbc7.

**Comment by drcxd** [comment] 2022-05-28 10:26
You are correct. It's the lsp-mode package I was using. After upgraded to one built in May 2022, the issue is gone. 
Sorry about all this, I'll make sure to upgrade anything to the latest before I turn to someone else.
Thanks for your kind help.
