### ISSUE TITLE
corfu overlay not closing "on select"

### ISSUE THREAD

**Issue by rileyrg** [minad/corfu#27] opened 2021-06-09 20:05 UTC
I'm literally using your exact config in the readme : orderless too.

lsp-completion-enable is on so lsp feeds completon-at-point.
c++-mode

I hit alt-tab to completion-at-point (completion-at-point-functions is the lsp capf) and corfu provides me completions - I can tab/arrow  around them, but return is not closing the dialog.

I realise how complex this can be with other configs, so is there anything really really obvious this might be before we get down to minimum configs etc?

![screenshot-latest](https://user-images.githubusercontent.com/362891/121421169-29cfc580-c96e-11eb-9a14-d43288a34a49.png)

**Comment by minad** [comment] 2021-06-10 08:45
I've never seen this. But I am not using the lsp capf. Is this a new issue which has been recently introduced by Corfu or LSP?

**Comment by Qkessler** [comment] 2021-06-10 08:53
Hi minad!

I have also seen this bug for the past two weeks. The issue has 
been with corfu in some of the modes, i.e. python-mode with lsp 
completion provided by CAPF.

What I’m experiencing is the same: instead of selecting a 
candidate with RET, corfu’s tooltip won’t close, while the 
candidate is added to the line.

Best,


On 2021-06-10, 10:45 +0200, Daniel Mendler 
***@***.***> wrote:

> I've never seen this. But I am not using the lsp capf. Is this a 
> new issue which has been recently introduced by Corfu or LSP?


-- 
Enrique Kessler Martínez

**Comment by rileyrg** [comment] 2021-06-10 09:50
TBH, it's the first time I have really tried to use corfu with anything in a programming mode, LSP or not since I updated my config to yours in the readme.  @Qkessler  thanks for the report - always nice to know we’re not alone ;)

**Comment by Qkessler** [comment] 2021-06-10 10:01
Sure! @rileyrg 
I have been using corfu for a while already for everything! I love its integration with dabbrev and its performance overall.
For some reason, I cannot reproduce it reliably, in some servers like lsp-java (uses eclipse's server) corfu works as expected, but after a while, it goes back to same erratic behaviour.
I really appreciate the work you are doing @minad, keep it up!

**Comment by minad** [comment] 2021-06-18 06:17
Did one of you manage to narrow down what is causing this? I really need a minimal configuration to try to reproduce this.

**Comment by Qkessler** [comment] 2021-06-18 15:02
Hi Daniel,

I still haven’t got around the keep poking into the configuration 
with lsp-mode to narrow the error down. I will try to find some 
time in the following days.

Thanks for the interest,

Best,

On 2021-06-18, 08:18 +0200, Daniel Mendler 
***@***.***> wrote:

> Did one of you manage to narrow down what is causing this? I 
> really need a minimal configuration to try to reproduce this.


-- 
Enrique Kessler Martínez

**Comment by rileyrg** [comment] 2021-06-23 09:12
Sorry, no. I had to stop using it for now.

**Comment by jdtsmith** [comment] 2021-07-18 21:55
I can confirm I've seen this behavior too, rarely. I'll see if I can find a way to reproduce.

**Comment by minad** [comment] 2021-09-29 13:02
I assume that this issue has been fixed by recent refactorings. Please let me know if you still see this.

**Closed by minad** 2021-09-29 13:02 UTC
