### ISSUE TITLE
`corfu` window (seemingly) leads to line jumps in split buffers if `lsp-mode` (and `flycheck`?) is active

### ISSUE THREAD

**Issue by Walheimat** [minad/corfu#210] opened 2022-07-31 16:57 UTC
# Scenario

In larger files I like to split a file's buffer so I can edit one section while seeing another. So it's likely not a problem for other people (and for me it's more of an inconvenience).

When I do this in a buffer that has `lsp-mode` and flycheck` enabled, it can happen that the buffer position changes to a line that has an error/warning in it.

I checked if this might be related to this `lsp-mode` issue: https://github.com/emacs-lsp/lsp-mode/issues/3607, but the behavior is the same with or without the suggested change.

I don't know if this is a `corfu` or a `lsp-mode` or a `flycheck` problem, but it doesn't happen if `corfu-mode` is off. It's not easy to recreate but I never managed if `corfu` was off. I looked if `lsp-ui` might be a problem but it happens with that turned off as well.

I tried to look into the profile when this happens but I really can't see how/where this would happen.

Hope someone with deeper understanding can help me out.

# Recreate

You will need `lsp-mode` setup (happens with most servers I tried) and on. Split the buffer. Deliberately create an error in the file. Edit the file somewhere else and see how it jumps back to the error line while writing.

# Configurations

Since it's possible (likely?) that my configuration is the culprit, I'm adding it here.

Here's my `corfu` configuration:

```elisp
(use-package corfu
  :custom
  (corfu-auto t)
  (corfu-quit-no-match t)
  (corfu-cycle t)
  :hook (prog-mode . corfu-mode))
```

Here's my `lsp-mode` config:

```elisp
(use-package lsp-mode
  :config
  (setq lsp-completion-provider :none)
  :custom
  (lsp-signature-render-documentation nil)
  (lsp-signature-function 'lsp-signature-posframe)
  (lsp-signature-auto-activate '(:on-server-request))
  (lsp-keep-workspace-alive nil))
```

Nothing customized for `flycheck`.

**Comment by minad** [comment] 2022-07-31 19:15
I am afraid I cannot help you here. It is more likely that the issue is caused by Lsp-mode/Flycheck than by Corfu. Why would Corfu jump to an error, of which it doesn't have any knowledge?

I asked the Lsp maintainer @yyoncho before if they are interested in testing Lsp-mode against Corfu in addition to Company. Corfu is a simple package, such that one could almost consider it a reference UI which relies on Capfs only. This makes it a good candidate to test Lsp-mode and other Capfs. On the other hand, Lsp-mode is a vastly more complex with many moving parts, which relies on different external servers. For this reason and due to lack of time, I cannot spend time on better support for Corfu+Lsp. Also implementation issues on the side of Lsp-mode like the aforementioned Capf issue should be fixed first.

As an alternative you could give Eglot with Flymake a try. Eglot provides a correct Capf implementation and it generally seems to have fewer issues, but this is most likely only due to its simplicity and lack of features.

**Closed by minad** 2022-07-31 19:15 UTC
