### ISSUE TITLE
Corfu completions on the wrong screen

### ISSUE THREAD

**Issue by WorldsEndless** [minad/corfu#235] opened 2022-09-30 18:23 UTC
When I invoke Corfu completions, the pop up is not under the place in which I am working but is on one of my other monitors (I work with three). Since I use exwm, sometimes those buffers are non-emacs windows like my browser. In that case, the candidates are nowhere visible.

**Comment by minad** [comment] 2022-09-30 22:20
Hmm, I have no idea. I'd love to help but I don't have multiple monitors and don't use exwm. Maybe this is either an Exwm bug or an Emacs bug (position computation in corfu--popup-show or corfu--make-frame)?

I close this as wontfix 🤷

**Closed by minad** 2022-09-30 22:20 UTC

**Comment by Stebalien** [comment] 2023-01-24 16:35
It's not pretty, but here's my solution:

```elisp
(define-advice corfu--make-frame (:around (fn frame x y w h b) exwm)
  (if exwm--connection
      (prog1
          (let ((inhibit-redisplay t)
                (geo (frame-monitor-geometry exwm-workspace--current)))
            ;; When we're positioning the corfu frame, make it relative
            ;; to the current monitor. The info frame will position
            ;; itself relative to corfu.
            (when (eq frame corfu--frame)
              (setq x (+ x (car geo))
                    y (+ y (cadr geo))))
            ;; Make sure corfu can see a parent frame, even if we've
            ;; removed it.
            (cl-letf (((symbol-function #'frame-parent)
                       (lambda (frame)
                         (or (frame-parameter frame 'parent-frame)
                             exwm-workspace--current))))
              (funcall fn frame x y w h b)))
        ;; Remove the parent frame.
        (set-frame-parameter frame 'parent-frame nil))
    (funcall fn frame x y w h b)))
```

**Comment by minad** [comment] 2023-12-29 16:51
I've added EXWM support in https://github.com/minad/corfu/commit/1c53066c413faac4afe853153fdb00475c3e4c78. At least the child frame overlay issue should be fixed, but probably not yet the multiple workspace issue.

**Comment by jsilve24** [comment] 2024-02-06 16:04
@Stebalien solution does help but if you end completion without selecting a candidate I am finding the completions frame hangs around and won't disappear until I restart emacs...

**Comment by minad** [comment] 2024-02-06 16:17
@jsilve24 I haven't tried EXWM on multiple monitors so far. But I plan to do this soon and then I will also address this issue.

**Comment by minad** [comment] 2024-02-06 17:16
@Stebalien I wonder if we can find a simpler fix. The problem is that we unparent the child frame for EXWM and frame-parent returns nil as a consequence. Could we instead store the original frame parent in a custom frame parameter corfu--exwm-parent when we unparent the child frame, and then use that parent instead? 

The consequence would be that the frame will be recreated when moving between monitors, but this is the same with non-EXWM setups if we move between parent frames. Instead of recreation, movement only should be sufficient. This could be improved in a second step.

**Comment by Stebalien** [comment] 2024-02-06 17:20
We could definitely do that. I'll take a look when I get back home (next week-ish, maybe).

**Comment by minad** [comment] 2024-02-06 17:25
@Stebalien Thanks! I have made a quick attempt at https://github.com/minad/corfu/compare/exwm-fix. It behaves as expected on my current single monitor setup. If you or @jsilve24 test this on multiple monitors, and it works, I could merge it right away.

**Comment by Stebalien** [comment] 2024-02-06 17:31
I'm pretty sure it won't work without manually specifying the location (I've tried in the past). But that patch is definitely an improvement as it'll keep corfu from flickering (constantly being re-created).

**Comment by minad** [comment] 2024-02-06 17:37
My assumption was that the child frame (before unparenting) is created at the correct location. But I think you are right that it won't work when we move the child frame, since then the upper corner of the first monitor is probably taken as reference point.

**Comment by jsilve24** [comment] 2024-02-06 17:38
Just tried the exwm-fix branch, didn't fix the issue.
