### ISSUE TITLE
Posframe window can get stuck if the cursor moves too fast

### ISSUE THREAD

**Issue by tralph3** [minad/corfu#462] opened 2024-05-21 20:20 UTC
In the attached video I tried to force the issue, but this is something that happens quite often. In about 1 hour it can happen about 5 or 6 times. Quite annoying.

The window just gets stuck and is entirely unresponsive. The only way to make it go away is to trigger another completion.

The issue seems to happen whenever Corfu is about to display the popup, but I move my cursor away quickly just before that.

https://github.com/minad/corfu/assets/41462117/fbe9b496-c2a1-405f-93e5-19b73225cfb6

**Comment by tralph3** [comment] 2024-05-21 20:21
This is my Corfu config:

```emacs-lisp
(use-package corfu
  :ensure t
  :custom
  (corfu-auto t)
  (corfu-auto-delay 0.2)
  (corfu-auto-prefix 0)
  (corfu-min-width 60)
  (corfu-popupinfo-delay 0.5)
  (corfu-preview-current nil)
  (corfu-preselect 'prompt)
  (corfu-quit-no-match t)
  (corfu-on-exact-match 'quit)
  (corfu-cycle t)
  :config
  (corfu-popupinfo-mode)
  (global-corfu-mode))
```

**Comment by minad** [comment] 2024-05-21 20:25
Duplicate of https://github.com/minad/corfu/discussions/453? Do you have a minimal recipe?

**Closed by minad** 2024-05-21 20:25 UTC
