### ISSUE TITLE
lsp-org

### ISSUE THREAD

**Issue by smalltimer** [minad/corfu#99] opened 2021-12-27 14:52 UTC
Hi, 
I use corfu with lsp-mode, orderless, and kind-icon, and the results are fantastic! I just discovered lsp-org (https://emacs-lsp.github.io/lsp-mode/manual-language-docs/lsp-org/), and while I can get lsp to trigger in the org file, I am not able to get completions from corfu in the source blocks. Is this something that is known? I am not very good with elisp, and am wondering whether this might just be me, failing to set some basic configuration variables.

**Comment by minad** [comment] 2021-12-27 16:21
I assume that this should work if you use the lsp-mode configuration by @jdtsmith. See https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode. But it could also be that additional tweaks are needed. @jdtsmith did you try lsp-org?

**Comment by jdtsmith** [comment] 2021-12-27 16:50
No I never saw that one, but since the OP is getting no completions at all, my guess is lsp-mode completions aren't working correctly in lsp-org.   Do completions work with company, or even just plain M-Tab style completion in a code src block (disabling both company and corfu)?

As an aside, it sounds quite challenging to get lsp-mode to behave on a mixed-mode file; it really wants to "own" the entire file.  Interestingly I've been playing with this very issue.  I'm exploring a very simple markdown + code cells idea, where the markdown cells are just multi-line strings or comments, and cells are delineated by special comments.  It's a mashup of polymode, outshine, and markdown-mode.  It's similar to [code-cells](https://github.com/astoff/code-cells.el)) but having the full power of markdown syntax from markdown-mode in those blocks.  The idea is that the source file remains fully syntactically valid, so things like lsp-mode are happy with it and need no special handling.  I'm using Python to start, but no reason you couldn't use with C-languages, ala:

```C
// * A code block header

<code>

// * A markdown block
/*
- Formatted as markdown
*/

// * Another code block

<code>

```

**Comment by minad** [comment] 2021-12-27 17:31
> As an aside, it sounds quite challenging to get lsp-mode to behave on a mixed-mode file; it really wants to "own" the entire file. 

There is an easy way out - just create a temporary file with only the code blocks.

**Comment by jdtsmith** [comment] 2021-12-27 18:51
> > As an aside, it sounds quite challenging to get lsp-mode to behave on a mixed-mode file; it really wants to "own" the entire file.
> 
> There is an easy way out - just create a temporary file with only the code blocks.

Right, and that's what lsp-org appears to do.  The problem is, the LSP protocol works by sending a snapshot of the file on first open, then sending incremental `didChange` updates for all the in-buffer changes.  Hence the [mentioned limitations](https://emacs-lsp.github.io/lsp-mode/manual-language-docs/lsp-org/#known-limitations).

**Comment by smalltimer** [comment] 2021-12-28 08:11
> No I never saw that one, but since the OP is getting no completions at all, my guess is lsp-mode completions aren't working correctly in lsp-org. Do completions work with company, or even just plain M-Tab style completion in a code src block (disabling both company and corfu)?

Aye, I am indeed using orderless and flex as per the documentation @minad linked - and it works very well in buffers with lsp-mode! I have not installed company (I don't know what it does exactly...), but the M-/ completions (dabbrev?) work in code src-blocks - but I don't get any popups - I think it's just emac's default completion. I should have reported this, but the corfu completions work seamlessly when used on the temporary file created by lsp-org. 

Btw, @jdtsmith , I am almost sure you've tried it - but if not, emacs-jupyter is the bees knees! I have used it with python and with julia and it works flawlessly - I am just about ready to stop using browser-based notebook interfaces like jupyter-lab, pluto etc. I am jumping ship the instant I get the completions working.

**Comment by minad** [comment] 2021-12-28 22:58
@smalltimer It sounds as if you didn't activate `corfu-global-mode` or `corfu-mode` in the org buffer? What do you mean by "the interface is rather plain"? Do you see the default `*Completions*` buffer instead of a Corfu popup?

**Comment by jdtsmith** [comment] 2021-12-29 21:15
company is just a corfu-alike (OK I couldn't resist ;).  It's the original, most widely used "in-buffer" pop-up completion-in-region UI.  Completion-at-point (usually M-Tab) is just the command you want, and it _should_ trigger corfu to pop-up.  

Maybe describe the exact steps you are taking to get partial, non-popup completion in your ORG-SRC blocks, and what those completions look like.

**Comment by minad** [comment] 2021-12-29 21:43
Isn't ac the original original Corfu-alike? ;)

**Comment by minad** [comment] 2021-12-29 23:48
@jdtsmith Btw, do you know https://github.com/astoff/code-cells.el?

**Comment by jdtsmith** [comment] 2021-12-30 05:50
Yep, that was in fact the inspiration.  I started by adding polymode for markdown to it.  Then added some workarounds to keep lsp-mode happy (with its need for `didChange`).  Then wanted better cell hierarchy support so reached for outshine, with some patches for better face-styling.  In the end there was not much left for it to do other than notebook import/export. I'm not thinking a mode, more of a "roll your own lsp-compatible cell-based pure-source-file literate format in a few easy steps" gist or something.

I haven't investigated emacs-jupyter.  Seems a lot of people are searching for solutions in this space — multiple modes in a buffer with completion and customized commands, lsp support, markdown/org literate action, cell hierarchy/organization [1], cell-based REPL commands, in-buffer results (over-rated IMO), etc.    Basically an escape from browser-based editing. 

Probably one package to rule them all would scratch a lot of itches.

[1] BTW, that gave me a thought about consult-outline: it might be too much of a UI departure, but if you could expand/collapse entire trees of the outline heirarchy, that would basically serve as a super-effective pop-up hierarchy browser/organizers.

**Comment by jdtsmith** [comment] 2021-12-30 05:56
I haven't tried ORG-BABEL, but I really like the idea of clean pure-source-files, with the markdown/whatever in block comments or strings.  lsp-mode is happy, you can compile or run the files as scripts from the command line without processing, share them with anyone, etc.  And of course export to HTML and all that.  I do tend to use markdown since my group is mostly familiar with it.  I haven't dove into the universe of org yet (despite knowing Carsten pretty well). 

Polymode is an interesting approach.  Once you get your head around the fact that it's really two (or more) completely separate buffers in action, such that getting modes (like outshine) to work in both of them requires copying over any buffer local variables from host to "inner" indirect buffers, it starts to make more sense.  Very fast and powerful.  Could definitely use better documentation, and the eieio code is somewhat inscrutable (as that flavor of code usually is to me).

**Comment by minad** [comment] 2021-12-30 14:02
> I haven't tried ORG-BABEL, but I really like the idea of clean pure-source-files, with the markdown/whatever in block comments or strings.

I would argue that such source files are not clean at all. But I agree that it is advantageous for the existing tooling if you use comments. For me Org is the way to go, it has most of the momentum and it is also working really well. I am not without criticism of course, Org has its messy sides and the package is huge. But overall a lot of maintenance is going into that package, so it gradually improves all the time.

> Probably one package to rule them all would scratch a lot of itches.

What exactly do you miss given the existing infrastructure? This is a hard question of course if you didn't try Org. I guess many people would argue that Org is that one package. But completion across source blocks is definitely a pain point. If lsp-org solves this, great!

> Polymode is an interesting approach.

I agree. But I am also not fond of its EIEIO internals and the complexity. My experience with it was a bit rough, so I went back to plain Org.

**Comment by jdtsmith** [comment] 2021-12-30 15:24
Good thoughts.  Since I work with students, I need to use something they can easily use, which means browser.  The default would be Jupyter notebooks.  

> > I haven't tried ORG-BABEL, but I really like the idea of clean pure-source-files, with the markdown/whatever in block comments or strings.
> 
> I would argue that such source files are not clean at all. But I agree that it is advantageous for the existing tooling if you use comments. For me Org is the way to go, it has most of the momentum and it is also working really well. 

By clean I simply mean they can be compiled/run/etc. without further modification.  Block level comments or multi-line strings are simply stripped away. How do you find org's tangling/weaving part in practice?  I should take a closer look. 

> > Probably one package to rule them all would scratch a lot of itches.
> 
> What exactly do you miss given the existing infrastructure? This is a hard question of course if you didn't try Org. I guess many people would argue that Org is that one package. But completion across source blocks is definitely a pain point. If lsp-org solves this, great!

(with the proviso that I haven't fully explored it):

1) portability to non-ORG users, and 
2) all the flycheck/linter/dynamic completion (and soon to be tree-sitter) stuff.  

I agree if lsp-org actually works well, this would remove much of the impetus for keeping source files "pure". Maybe they can even figure out an algorithm to juggle a number of derived files with incremental changes.  Only tricky bit it would seem is changes which cross section boundaries.

**Comment by smalltimer** [comment] 2021-12-30 17:12
Hi both, sorry I am on a time-critical project (year-end and so forth) so I have gone with company-mode which worked out of the box with emacs-jupyter. Company is decidedly uglier :D 

But I am very glad to see this conversation. I am not an elisp coder so I am reading about a lot of things for the first time. Yeah, emacs-jupyter is aimed at a single-language literate notebook-type scenario - essentially providing an alternative to jupyter/pluto notebooks without the need to launch a 500MB-RAM-consuming, perenially-spying, attention-and-data-mining object that is the modern web browser.

@jdtsmith the fact that you have convinced (coerced? forced? :D) your students to use emacs is very impressive! I can't get mine to even consider installing it... Even if they did, I don't have the elisp expertise to trouble-shoot their problems if/when they were to run into some. If it's some maths/engineering style problems where your notebooks form a coherent story from one cell to another, I'd deffo have a look at emacs-jupyter! Of course, I have only tried two languages and if you're using something other than python or julia, your mileage will vary. 

I hope I haven't disappointed you guys too much moving to company. I also realise I didn't provide enough details about the issue for you to actually give me constructive feedback on how to deal with it. I will come back to corfu in a couple of months or so! Just that right now I'm trying to finish off two papers simultaneously before changing labs... I'm happy to close the issue and re-raise it when I can file a more detailed report.

**Comment by minad** [comment] 2021-12-30 18:24
Okay, let's close this then. I am not disappointed. This is expected. Corfu currently requires a bit of fiddling, in particular with lsp-mode. The issue is that lsp-mode/lsp-org etc support Company out of the box (they even auto configure it). Maybe we can convince them in the future to consider alternative frontends and also test against them.

**Closed by minad** 2021-12-30 18:24 UTC
