### ISSUE TITLE
Jumbled letters

### ISSUE THREAD

**Issue by salutis** [minad/corfu#151] opened 2022-04-01 05:39 UTC
In certain modes, Corfu jumbles up letters when I type fast.

I found the following closed issue that matches my experience:

https://github.com/minad/corfu/issues/106

> There is one thing I can help with if you tell me the completion backend you are using. Do you use lsp mode, eglot or some other capf? Then I could review if the backend itself could be causing this.

I observe the problem when typing inside of larger Scheme libraries with Geiser.

The `completion-at-point-functions` variable contains:

- `geiser-completion--for-symbol`
- `geiser-completion--for-module`
- `geiser-completion--for-filename`

When I type `make` super-fast, Corfu changes it to `makake`.

The bug also happens under`emacs -Q` with just Geiser and Corfu installed.

Company does have the problem (in the exact same situation).

Any ideas?

**Comment by minad** [comment] 2022-04-01 10:47
I never observed this issue. Corfu should not insert the characters itself as already mentioned in #106. Can you narrow the issue down more by reducing the set of completion functions? I assume it also happens for `geiser-completion--for-symbol` only? Also please specify your configuration more precisely. How does this happen exactly? I assume you have `corfu-auto=t`? You type `make`, the popup comes up (or not?) and then you end up with `makake`? Do you also use MacOS? Did you report the Company issue too? One thing which could help me is your `view-lossage` output. How does it look after such an issue occurred?

~~~
 m             ;; self-insert-command
 a             ;; self-insert-command
 k             ;; self-insert-command
 e             ;; self-insert-command
~~~

**Comment by minad** [comment] 2022-04-01 10:58
I inspected the Geiser Capf. At first sight it does seem benign, but there is IPC going on with the background process and I didn't read through all the details. It could be that there is something going on which leads to issues in Corfu. As an experiment, you can try some Cape sanitizers:

~~~ elisp
(setq completion-at-point-functions
      (list (cape-capf-purify (cape-capf-noninterruptible #'geiser-completion--for-symbol))))
~~~

* cape-capf-purify ensures that the Capf does not insert content itself into the buffer
* cape-capf-noninterruptible protects the Capf from interruption

**Comment by jilen** [comment] 2022-04-01 10:59
I guess it might related to `childframe`

**Comment by minad** [comment] 2022-04-01 11:11
> I guess it might related to childframe

Yes, that could be. Then it is an Emacs issue, maybe specific to MacOS. But @salutis claims that he observed the issue with Company too. Company does not use a child frame. Can you point me to the pyim issue where this was reported? (Doesn't matter if the report is in Chinese since we can translate it). Maybe @tumashu could also elaborate on this issue?

In order to debug this one has to inspect the input events which are processed by Emacs. The issue should be observable there. We should see duplicated input events in that case. One can try the aforementioned `view-lossage` or the `(recent-keys)` function. In the worst case one has to drop to the C layer and add some logging to the command loop where the input events are read.

**Comment by jilen** [comment] 2022-04-01 11:12
@minad Haven't see anyone report it yet. It use popup by default. Seems I am the only one encounter this.

**Comment by minad** [comment] 2022-04-01 11:14
Okay, @jilen can you inspect `view-lossage` or `(recent-keys)` to check for duplicated input events when you observe the issue?

> There is a company-posframe don't know he/she have it installed.

Sure, this could be. I assumed that @salutis tried a minimal setup but this may not be the case.

**Comment by jilen** [comment] 2022-04-01 11:17
I've tired logging the keyboard input to file while I first report this issue.
The key sequence in log file is correct.

**Comment by minad** [comment] 2022-04-01 11:20
@jilen Okay, I need more input to investigate this issue. Let's wait for @salutis to provide more information.

One more thing you could try: Try to reproduce the issue in an Elisp scratch buffer in emacs -Q where you only activated `corfu-mode`, nothing else! This way we could exclude any kind of Capf involvement and we could be sure that the issue is indeed due to Corfu or the child frame.

**Comment by jaor** [comment] 2022-04-01 17:50
On Fri, Apr 01 2022, Daniel Mendler wrote:

> I inspected the Geiser Capf. At first sight it does seem benign, but
> there is IPC going on with the background process and I didn't read
> through all the details.

Yes, there is IPC going on, but it's synchronous.  More concretely, a
message is sent to the scheme process and the results parsed to produce
the completion list; so it is bound to be a relatively slow operation,
compared to typical cases.  I think @salutis also mentioned somewhere
that the problem is more frequent in big buffers, which (i presume) will
give rise to more completions and make it slower.

(BTW, i *think* @salutis made a typo and he meant that the issue is /not/
present in company, but surely he'll clarify).

Cheers,
jao
-- 
Configuring Emacs is more of a lifestyle choice than a task that one
completes.  – Stephen A. Ramsey

**Comment by minad** [comment] 2022-04-01 18:05
> Yes, there is IPC going on, but it's synchronous.  More concretely, a
> message is sent to the scheme process and the results parsed to produce
> the completion list; so it is bound to be a relatively slow operation,
> compared to typical cases.  I think @salutis also mentioned somewhere
> that the problem is more frequent in big buffers, which (i presume) will
> give rise to more completions and make it slower.

Okay, thanks! The thing that matters is that the
completion-at-point-function is interruptible. This means even if the
function is interrupted during its execution, it should not enter an
invalid state or lead to observable side effects. From what I've seen
the Geiser capf is interruptible, since all operations are nicely
wrapped by save-excursion, unwind-protect etc. For non-interruptible
Capfs one could use cape-capf-noninterruptible as a wrapper.

In my experiments I didn't observe any issues with the Geiser completion
function in Scheme buffers.

> (BTW, i *think* @salutis made a typo and he meant that the issue is /not/
> present in company, but surely he'll clarify).

Yes, I also suspect that. This fits to what @jilen said about the child
frame causing the issue.

**Comment by minad** [comment] 2022-04-02 00:04
Original issue at https://gitlab.com/emacs-geiser/geiser/-/issues/42. @salutis please always link to related issues since this can give valuable information. It is not guaranteed that I find such an issue myself and things are usually connected. In this particular case I am stepping in the dark. The culprit could be either Corfu, the low level child frame machinery or Geiser.

**Comment by salutis** [comment] 2022-04-03 08:56
Before I answer all the questions: Thank you everyone for helping out!

> Can you narrow the issue down more by reducing the set of completion
functions? I assume it also happens for
\`geiser-completion&#x2013;for-symbol\` only?

The Makake bug remains alive after:

`(setq completion-at-point-functions '(geiser-completion--for-symbol))`

> Also please specify your configuration more precisely. How does this
happen exactly? I assume you have \`corfu-auto=t\`? Do you adjust other
Corfu settings?

The configuration:

    (require 'corfu)
    (setq corfu-auto t
          corfu-auto-prefix 1)
    (setq corfu-auto-delay 0.001
          corfu-echo-documentation t)

> You type \`make\`, the popup comes up (or not?) and then you end up
with \`makake\`?

The popup does *not* show.

> Do you also use MacOS?

Unfortunately.

> Did you report the Company issue too?

> [&#x2026;] @salutis made a typo and he meant that the issue is *not*
present in company, but surely he'll clarify.

I apologize!  Yes, the bug does *not* exist with `company-mode` nor
`company-box-mode`.

> One thing which could help me is your `view-lossage` output. How does
it look after such an issue occurred?

    (	       ;; self-insert-command
     m	       ;; self-insert-command
     a	       ;; self-insert-command
     k	       ;; self-insert-command
     a	       ;; self-insert-command
     k	       ;; self-insert-command
     e	       ;; self-insert-command

> As an experiment, you can try some Cape sanitizers:

**IMPORTANT: The sanitizer fixes the Makake bug!**

> I assumed that @salutis tried a minimal setup but this may not
be the case.

> Try to reproduce the issue in an Elisp scratch buffer in `emacs -Q`

I used the following configuration, evaluated after `emacs -Q`:

> Do not ask before evaluating code.
>
>     (setq org-confirm-babel-evaluate nil)
>
> Configure the package manager.
>
>     (require 'package)
>     (setq package-check-signature nil)
>     (add-to-list 'package-archives
>                  '("melpa" . "<https://melpa.org/packages/>"))
>     (defun my/package-ensure-installed (package)
>       (unless (package-installed-p package)
>         (package-install package)))
>     (package-initialize)
>     (package-refresh-contents)
>
> Fix macOS.
>
>     (my/package-ensure-installed 'exec-path-from-shell)
>     (setq exec-path-from-shell-variables '("PATH" "MANPATH" "LC<sub>ALL</sub>"))
>     (require 'exec-path-from-shell)
>     (exec-path-from-shell-initialize)
>
> Geiser.
>
>     (my/package-ensure-installed 'geiser)
>     (my/package-ensure-installed 'geiser-guile)
>     (require 'geiser)
>     (require 'geiser-guile)
>     (setq geiser-default-implementation 'guile
>           geiser-autodoc-delay 0.001
>           geiser-mode-start-repl-p t)
>
> Corfu.
>
>     (my/package-ensure-installed 'corfu)
>     (require 'corfu)
>     (setq corfu-auto t
>           corfu-auto-prefix 1)
>     (setq corfu-auto-delay 0.001
>           corfu-echo-documentation t)
>
> Company.
>
>     (my/package-ensure-installed 'company)
>     (my/package-ensure-installed 'company-box)
>     (setq company-idle-delay 0.001)

> @salutis please always link to related issues since this can give
valuable information. It is not guaranteed that I find such an issue
myself and things are usually connected. In this particular case I am
stepping in the dark.

I will, and I apologize.  Thank you for your wise guidance!

**Comment by minad** [comment] 2022-04-03 09:50
@salutis Thank you for the details. This matches most of my suspicions.

1. Your `view-lossage` output is clearly wrong. It shows duplicated input events `makake` which hints at an deeper underlying issue of the input handling - in other words, a bug in Emacs. The bug could be specific to MacOS and/or could be triggered only in combination with child frames.

2. Since the Cape sanitizer fixes the bug, we can conclude that either the Geiser Capf is non-interruptible or that using `while-no-input` exposes the underlying bug in the input handling. I need one more detail - please try the following three sanitizer configurations and tell me which of the configurations fix the issue.

~~~ elisp
;; config 1: only purify
(setq completion-at-point-functions 
  (list (cape-capf-purify #'geiser-completion--for-symbol)))

;; config 2: only noninterruptible
(setq completion-at-point-functions
  (list (cape-capf-noninterruptible #'geiser-completion--for-symbol)))

;; config 3: both
(setq completion-at-point-functions
  (list (cape-capf-noninterruptible (cape-capf-purify #'geiser-completion--for-symbol))))
~~~

3. You use a `corfu-auto-delay` setting of 0.001. You could as well use just 0, but such low values are discouraged, since they can lead to performance issues due to the constant completion candidate fetching. You also reported performance issues in
https://gitlab.com/emacs-geiser/geiser/-/issues/42. However in our case here, the low value exposes a bug in the input system or the Capf which is  a good thing. :)

Now regarding our next steps: I hope we can simplify the Geiser Capf and completion facilities first. See https://gitlab.com/emacs-geiser/geiser/-/issues/43 where I prepared an initial patch. Subsequently we can analyze the Capf a bit closer to check where potential non-interruptibility issues come into play. When I inspected the Capf the last time, I didn't see any obvious flaws, so it could as well be a deeper issue which is only exposed due to the process handling/interruptibility/MacOS. The process handling and event handling code in Emacs is complex and I have observed issues with it before. For example Emacs does not handle multiple consult-ripgrep processes well, which generate a lot of output. Therefore I do not rule out that there is not something wrong there. After figuring this out we can also look into improving Orderless support of the Geiser Capf, see https://gitlab.com/emacs-geiser/geiser/-/issues/42.

Because the sanitizers fix the issue we can essentially rule out that Corfu is at fault here. For now as a workaround, you can either use the Cape sanitizers (this is what they are there for!) or use a larger value of `corfu-auto-delay`. To emphasize this again - such a small value of the auto delay will lead to many problems down the road. I consider this a misconfiguration since it pushes the limits too far. Many completion backends don't handle this well and will slow Emacs down greatly. It will feel as if you are typing through molasses. The problem performance issues will get more pronounced in combination with `cape-capf-noninterruptible` which enforces that the completion candidate generation completes without interruption.

**Comment by minad** [comment] 2022-04-03 10:07
Since the popup doesn't appear it could be that child frames are not involved here. But we should still try rule out any involvement. @salutis please try the following four configurations:

~~~ elisp
;; config 4.0: no child frame, no sanitizers
(advice-add #'corfu--make-frame :override #'ignore)

;; config 4.1: no child frame, only purify
(advice-add #'corfu--make-frame :override #'ignore)
(setq completion-at-point-functions 
  (list (cape-capf-purify #'geiser-completion--for-symbol)))

;; config 4.2: no child frame, only noninterruptible
(advice-add #'corfu--make-frame :override #'ignore)
(setq completion-at-point-functions 
  (list (cape-capf-noninterruptible #'geiser-completion--for-symbol)))

;; config 4.3: no child frame, both sanitizers
(advice-add #'corfu--make-frame :override #'ignore)
(setq completion-at-point-functions
  (list (cape-capf-noninterruptible (cape-capf-purify #'geiser-completion--for-symbol))))
~~~

**Comment by salutis** [comment] 2022-04-03 10:18
@minad 

The results:

- 4.0 — bug present
- 4.1 — bug present
- 4.2 — bug absent
- 4.3 — bug absent

(Tested `emacs -Q` with the Emacs configuration I listed above. I typed `C-g` 5 times before each test. Emacs rang the bell for each `C-g`.)

**Comment by minad** [comment] 2022-04-03 10:18
@salutis What about configurations 1, 2, 3 from https://github.com/minad/corfu/issues/151#issuecomment-1086825462?

**Comment by salutis** [comment] 2022-04-03 10:23
@minad 

The results for the earlier tests:

- 1 — present
- 2 — absent
- 3 — absent

**Comment by salutis** [comment] 2022-04-03 10:24
(I reset Emacs [`-q`] between the two sequences of tests.  In other words, I tested 1, 2, and 3 without the `advice-add`.)

**Comment by minad** [comment] 2022-04-03 11:11
@salutis Okay, good. So we can conclude that child frames don't play a relevant role here. Furthermore the issue occurs purely due to interruption of the Capf. Note that Company does not interrupt completion backends or Capfs, which avoids the issue. As mentioned before, our tests leave two possibilities:

1. The Geiser Capf is flawed and non-interruptible due to wrong API use. We should be able to exclude this possibility by giving the Geiser Capf a closer look.
2. If the Geiser Capf uses all APIs correctly, such that no interruption side effects should be observable (e.g., by using `save-excursion`, `unwind-protect`, etc.), then the issue is in an underlying API. It could be that the Emacs process APIs don't like interrupts in their process filters or sentinels on the Elisp layer. It could also be a deeper issue in the C code. This is plausible since I didn't observe anything out of the ordinary in my tests on Linux, while you observed the problem on Mac. I am not sure by how much the process handling differs between these systems. While Linux and Mac both offer the usual Posix process handling APIs, they also come with their own APIs (epoll on Linux) and (kqueue on BSD). A quick grep through the Emacs code base at least revealed that kqueue is used, so it is likely that the process handling differs between these operating systems.

Since Capf interruption is the root cause here, which triggers the issues, let me summarize the reasons for this Corfu behavior:

- Interruption of the Capf is the only possibility to achieve low latency, since the Capf and completion table APIs are synchronous APIs.

- Completion tables must be pure functions (and thus interruptible) since this is how they are used in Icomplete (https://github.com/emacs-mirror/emacs/blob/441ce4672d4aab14d1bef078692fec7ad4ff0c0a/lisp/icomplete.el#L723). In Vertico I also treat completion tables as interruptible and didn't observe issues so far. The definition of the `completing-read` API (or the completion table) API hints at the tables being pure functions. Note that the Geiser completion table is trivially pure since it is a list of completion candidates. 

- The documentation of `completion-at-point-functions` hints at the Capfs being pure (without observable side effects and thus being interruptible):

> As is the case with most hooks, the functions are responsible for
> preserving things like point and current buffer.
> 
> NOTE: These functions should be cheap to run since they're sometimes
> run from post-command-hook; and they should ideally only choose
> which kind of completion table to use, and not pre-filter it based
> on the current text between START and END.

(This NOTE is already violated by the Geiser Capf since the Geiser Capf prefilters the candidates early on. This is also what leads to broken Orderless support, see https://gitlab.com/emacs-geiser/geiser/-/issues/42. However the question here is why purity is violated too.)

- Some of the reference Capfs (e.g. `elisp-completion-at-point`) are interruptible.

- I acknowledge that Corfu takes an uncompromising stance here. Corfu expects the Capfs to be implemented in a robust way and correctly. In order to handle Capfs which do not satisfy these requirements, one can use the Cape sanitizers, in particular `cape-capf-noninterruptible` (or the `:around` advice version `cape-wrap-noninterruptible`). Unfortunately broken Capfs exist in the wild as this issue shows. Even Emacs itself comes with Capfs, which are broken in worse ways, the most problematic example is `pcomplete-completions-at-point`, which even writes to the buffer, which is illegal. Fortunately we can tame this Capf with the `cape-capf-purify` sanitizer (https://github.com/minad/corfu#completing-with-corfu-in-the-eshell-or-shell).

I close the issue here. Let's proceed with the debugging on the side of Geiser. See https://gitlab.com/emacs-geiser/geiser/-/issues/42, https://gitlab.com/emacs-geiser/geiser/-/issues/43 and https://gitlab.com/emacs-geiser/geiser/-/merge_requests/7.

**Closed by minad** 2022-04-03 11:11 UTC
Labels: unconfirmed

**Comment by jilen** [comment] 2022-04-27 06:54
I've switch from `https://github.com/d12frosted/homebrew-emacs-plus` to `emacs macport` recent days.
And `emacs-macport` seems not have this issue. Hope it helpful if someone encounter this wired bug.

**Comment by salutis** [comment] 2022-05-20 15:29
@minad I forgot to say *thank you*.
